Repository betagouv/beta.gouv.fr, pull requests merged in 2020-06, with the labels that each got.

#3778 Création de mobiville dans Produit !
  content/_startups/mobiville.md
Labels: netlify-cms/pending_publish

#3775 Création de benjamin.berut dans Membre !
  content/_authors/benjamin.berut.md
Labels: netlify-cms/pending_publish

#3783 Création de kadri.kaldmae dans Membre !
  content/_authors/kadri.kaldmae.md
Labels: netlify-cms/pending_publish

#3784 Création de camille.fretier dans Membre !
  content/_authors/camille.fretier.md
Labels: netlify-cms/pending_publish

#3785 Mise à jour de kathleen.marie-joseph dans Membre
  content/_authors/kathleen.marie-joseph.md
Labels: netlify-cms/pending_publish

#3786 Création de claude.pereira-leconte dans Membre !
  content/_authors/claude.pereira-leconte.md
Labels: netlify-cms/pending_publish

#3789 Création de estime dans Produit !
  content/_startups/estime.md
Labels: netlify-cms/pending_publish

#3793 Mise à jour de juliette.fracchiolla-hurstel dans Membre
  content/_authors/juliette.fracchiolla-hurstel.md
Labels: netlify-cms/pending_publish

#3795 Création de sophie.hivert dans Membre !
  content/_authors/sophie.hivert.md
Labels: netlify-cms/pending_publish

#3820 Création de vincent.maubert dans Membre !
  content/_authors/vincent.maubert.md
Labels: netlify-cms/pending_publish

#3822 Mise à jour de manon.de-benaze dans Membre
  content/_authors/manon.de-benaze.md
Labels: netlify-cms/pending_publish

#3823 Mise à jour de anne.pichon dans Membre
  content/_authors/anne.pichon.md
Labels: netlify-cms/pending_publish

#3824 Mise à jour de pieterjan.montens dans Membre
  content/_authors/pieterjan.montens.md
Labels: netlify-cms/pending_publish

#3596 création de la fiche PSP portail suivi des plaintes
  content/_authors/david.auroi.md
  content/_startups/psp.md
Labels: En discussion

#3828 Création de yoann.kassi-vivier dans Membre !
  content/_authors/yoann.kassi-vivier.md
Labels: netlify-cms/draft

#3760 Mise à jour du manifeste beta.gouv.fr
  _pages/programme/incubateurs.md
  _pages/programme/manifeste.md
Labels: needs consensus

#3834 Création de gabrielle.bouxin dans Membre !
  content/_authors/gabrielle.bouxin.md
Labels: netlify-cms/pending_publish

#3841 Mise à jour de nicolas.bouilleaud dans Membre
  content/_authors/nicolas.bouilleaud.md
Labels: netlify-cms/pending_publish

#3591 création fiche produit covoit scellé
  content/_authors/joy.franchini.md
  content/_startups/covoit'scelles.md
Labels: En discussion

#3594 création fiche PSIJ
  content/_authors/nicolas.boulio.md
  content/_authors/olivier.charrier.md
  content/_startups/psij.md
Labels: En discussion
