Repository betagouv/beta.gouv.fr, pull requests merged in 2020-11, with the labels that each got.

#4519 Création de justif dans Produit !
  content/_startups/justif.md
Labels: netlify-cms/pending_review

#4531 Mise à jour de justif dans Produit
  content/_startups/justif.md
Labels: netlify-cms/pending_publish

#4532 Mise à jour de paul.marcade dans Membre
  content/_authors/paul.marcade.md
Labels: netlify-cms/pending_publish

#4533 Mise à jour de helene.franceschin dans Membre
  content/_authors/helene.franceschin.md
Labels: netlify-cms/pending_publish

#4534 Mise à jour de felicie.callipel dans Membre
  content/_authors/felicie.callipel.md
Labels: netlify-cms/pending_publish

#4535 Création de labels.de.transition.ecologique dans Produit !
  content/_authors/anne.poirot.md
  content/_startups/labels-transition.md
Labels: netlify-cms/pending_publish

#4571 Mise à jour de e-mjpm dans Produit
  content/_startups/e-mjpm.md
Labels: netlify-cms/pending_publish

#4596 Mise à jour de victoria.martinez dans Membre
  content/_authors/victoria.martinez.md
Labels: netlify-cms/pending_publish

#4605 Mise à jour de justif dans Produit
  content/_startups/justif.md
Labels: netlify-cms/pending_publish

#4599 Mise à jour de anne.becquet dans Membre
  content/_authors/anne.becquet.md
Labels: netlify-cms/draft

#4593 Création de egalite.professionnelle.1 dans Produit !
  content/_startups/egalite.professionnelle.md
Labels: netlify-cms/pending_publish

#4619 Mise à jour de tristan.roue dans Membre
  content/_authors/tristan.roue.md
Labels: netlify-cms/pending_publish

#4634 Update jean-yves.stervinou.md
  content/_authors/jean-yves.stervinou.md
Labels: merge it !

#4622 Update vincent.agnano.md
  content/_authors/vincent.agnano.md
Labels: merge it !

#4633 Recrutement d'un.e bizdév. stagiaire pour Trackdéchets
  content/_jobs/2020-11-28-Trackdéchets_stagebizdév.md
Labels: merge it !

#4629 Recrutement terminé
  content/_jobs/2020-11-06-mobilic recrute un·e business developer.md
Labels: merge it !

#4621 Traduction
  content/_jobs/2020-11-04-recrutement-bizdevs-beta.md
  content/_jobs/2020-11-04-recrutement-devs-beta.md
Labels: merge it !

#4637 Update eric.heijligers.md
  content/_authors/eric.heijligers.md
Labels: merge it !

#4602 Mise à jour de maxime.basset dans Membre
  content/_authors/maxime.basset.md
Labels: modifications nécessaires, netlify-cms/draft

#4639 Création de dumas dans Produit !
  content/_startups/dumas.md
Labels: netlify-cms/pending_publish

#4642 Mise à jour de raphael.pierquin dans Membre
  content/_authors/raphael.pierquin.md
Labels: netlify-cms/pending_publish

#4640 Mise à jour de christophe.musitelli dans Membre
  content/_authors/christophe.musitelli.md
Labels: netlify-cms/pending_publish

#4641 Mise à jour de marina.wiesel dans Membre
  content/_authors/marina.wiesel.md
Labels: netlify-cms/pending_publish

#4643 Mise à jour de lery.jicquel dans Membre
  content/_authors/lery.jicquel.md
Labels: netlify-cms/pending_publish
