Repository betagouv/beta.gouv.fr, pull requests merged in 2020-12, with the labels that each got.

#4606 Création de archifiltre dans Produit !
  content/_startups/archifiltre.md
  content/_startups/labonneplace.md
  content/templates/startups.md
  rb/schema/startups.yml
Labels: En discussion, netlify-cms/pending_review

#4683 Update raphael.odini.md
  content/_authors/raphael.odini.md
Labels: merge it !

#4617 Création de inca dans Produit !
  content/_startups/inca.md
Labels: En discussion, netlify-cms/draft

#4653 Rename maitena.szobel.md to maitena.szkobel.md
  content/_authors/maitena.szkobel.md
Labels: merge it !

#4656 mise à jour date de fin
  content/_authors/yann.klis.md
Labels: merge it !

#4691 Création de 1000.jours dans Produit !
  content/_startups/1000.jours.md
Labels: En discussion, netlify-cms/pending_review

#4699 Mise à jour de elodie.desbat dans Membre
  content/_authors/elodie.desbat.md
Labels: netlify-cms/pending_publish

#4701 Mise à jour de maritza.abreo dans Membre
  content/_authors/maritza.abreo.md
Labels: netlify-cms/pending_publish

#4686 Création de mano dans Produit !
  content/_startups/mano.md
Labels: En discussion, netlify-cms/pending_review

#4713 Mise à jour de julien.rayneau dans Membre
  content/_authors/julien.rayneau.md
Labels: netlify-cms/pending_publish

#4720 Mise à jour de victoria.martinez dans Membre
  content/_authors/victoria.martinez.md
Labels: netlify-cms/pending_publish

#4723 Mise à jour de chloe.moser dans Membre
  content/_authors/chloe.moser.md
Labels: netlify-cms/pending_publish

#4724 Mise à jour de clement.berthou dans Membre
  content/_authors/clement.berthou.md
Labels: netlify-cms/pending_publish

#4725 Mise à jour de saniya.al_saadi dans Membre
  content/_authors/saniya.al_saadi.md
Labels: netlify-cms/pending_publish

#4726 Mise à jour de thibaut.larrede dans Membre
  content/_authors/thibaut.larrede.md
Labels: netlify-cms/pending_publish

#4704 Mise à jour de jerome.desboeufs dans Membre
  content/_authors/jerome.desboeufs.md
Labels: netlify-cms/pending_publish

#4721 Création de monsuivipsy dans Produit !
  content/_startups/monsuivipsy.md
Labels: netlify-cms/pending_publish

#4703 Mise à jour de alexia.gazel dans Membre
  content/_authors/alexia.gazel.md
Labels: netlify-cms/draft

#4717 Mise à jour de anne-laure.pilloy dans Membre
  content/_authors/anne-laure.pilloy.md
Labels: netlify-cms/pending_publish

#4722 Mise à jour de benjamin.morali dans Membre
  content/_authors/benjamin.morali.md
Labels: netlify-cms/pending_publish

#4697 Ajoute page investigation "Culture Amateurs"
  content/_startups/culture_amateurs.md
Labels: merge it !

#4728 Mise à jour de celine.kniebihler dans Membre
  content/_authors/celine.kniebihler.md
Labels: modifications nécessaires, netlify-cms/pending_publish

#4688 Update alumni.md
  content/_phases/alumni.md
Labels: En discussion

#4684 Maj realisations 2020
  content/_startups/anotea.md
  content/_startups/chauffage-urbain.md
  content/_startups/clara.md
  content/_startups/e-controle.md
  content/_startups/mrs.md
  content/_startups/signalement.md
  content/_startups/zam.md
  content/_startups/zen.md
Labels: En discussion

#4731 Update alpha.md
  _pages/programme/formation/alpha.md
Labels: En discussion

#4749 Mise à jour de pierre-olivier.mauguet dans Membre
  content/_authors/pierre-olivier.mauguet.md
Labels: netlify-cms/pending_publish

#4758 Mise à jour de guillaume.houzel dans Membre
  content/_authors/guillaume.houzel.md
Labels: netlify-cms/draft

#4638 Create Plateforme-CSIRT.md
  content/_startups/Plateforme-CSIRT.md
Labels: En discussion

#4765 Update nathalie.reyre.md
  content/_authors/nathalie.reyre.md
Labels: modifications nécessaires

#4763 Création de rdv.consulat dans Produit !
  content/_startups/rdv.consulat.md
Labels: En discussion, netlify-cms/pending_review

#4772 Mise à jour de thibault.desjardins dans Membre
  content/_authors/thibault.desjardins.md
Labels: netlify-cms/draft

#4778 Mise à jour de morgan.izquierdo dans Membre
  content/_authors/morgan.izquierdo.md
Labels: netlify-cms/pending_publish

#4626 Fin du partenariat Kelrisks
  content/_startups/kelrisks.md
  content/_startups/mes-aides.md
Labels: En discussion

#4823 Mise à jour de alexandre.grimault dans Membre
  content/_authors/alexandre.grimault.md
Labels: netlify-cms/pending_publish

#4834 Mise à jour de maritza.abreo dans Membre
  content/_authors/maritza.abreo.md
Labels: netlify-cms/draft

#4837 Mise à jour de nicolas.mouanga dans Membre
  content/_authors/nicolas.mouanga.md
Labels: netlify-cms/pending_publish
