Repository betagouv/beta.gouv.fr, pull requests merged in 2020-04, with the labels that each got.

#3544 Mise à jour de la fiche de alexandre.grimault
  content/_authors/alexandre.grimault.md
Labels: netlify-cms/pending_publish

#3303 Bienvenue à xaviera.mcgown !
  content/_authors/xaviera.mcgown.md
Labels: netlify-cms/draft

#3424 Mise à jour de la fiche de claire.vigier
  content/_authors/claire.vigier.md
Labels: netlify-cms/draft

#3590 Mise à jour de la fiche de sandra.chakroun
  content/_authors/sandra.chakroun.md
Labels: netlify-cms/draft

#3599 Mise à jour de la fiche de claire.vigier
  content/_authors/claire.vigier.md
Labels: netlify-cms/pending_publish

#3627 Utilise de nouveaux termes pour les phases
  _data/menu.yml
  _includes/card-startup.html
  _layouts/dashboard.html
  _layouts/startups.html
  _pages/stats.md
  api/v1.3/startups.json
  api/v1.4/startups.json
  api/v1.5/startups.json
  api/v1.6/startups.json
  api/v1.7/startups.json
  assets/additional/style/grid.css
  content/_phases/acceleration.md
  content/_phases/alumni.md
  content/_phases/consolidation.md
  content/_phases/construction.md
  content/_phases/death.md
  content/_phases/investigation.md
  content/_phases/success.md
  content/_startups/aeris.md
  content/_startups/api-drones.md
  content/_startups/api-entreprise.md
  content/_startups/api-geo.md
  content/_startups/api-particulier.md
  content/_startups/api.gouv.fr.md
  content/_startups/assec.md
  content/_startups/auvol.md
  content/_startups/ban.md
  content/_startups/bourse.md
  content/_startups/boussole.md
  content/_startups/cobot.md
  content/_startups/data.gouv.fr.md
  content/_startups/demarches-simplifiees.fr.md
  content/_startups/dossiersco.md
  content/_startups/eac.md
  content/_startups/etudiant-entrepreneur.md
  content/_startups/fiches-de-banc.md
  content/_startups/filharmonic.md
  content/_startups/fluctuat.md
  content/_startups/geo.data.gouv.fr.md
  content/_startups/la-bonne-boite.md
  content/_startups/la-bonne-formation.md
  content/_startups/leximpact.md
  content/_startups/maintenant.md
  content/_startups/mdph.md
  content/_startups/memo.md
  content/_startups/mes-aides.md
  content/_startups/mpal.md
  content/_startups/mps.md
  content/_startups/ogptoolbox.md
  content/_startups/pass-culture.md
  content/_startups/permis-de-construire-facile.md
  content/_startups/pix.md
  content/_startups/pop.md
  content/_startups/psi.md
  content/_startups/retraite.md
  content/_startups/reuni.md
  content/_startups/trait-d-union.md
  content/_startups/tremplin.md
  content/_startups/urbaclic.md
  content/_startups/voir-et-localiser.md
Labels: needs consensus

#3648 Mise à jour de la fiche de adrien.di_pasquale
  content/_authors/adrien.di_pasquale.md
  rb/schema/authors.yml
Labels: netlify-cms/pending_review

#3652 Mise à jour de content/_authors/thomas.guillet.md
  content/_authors/thomas.guillet.md
Labels: netlify-cms/pending_review
