Repository betagouv/beta.gouv.fr, pull requests merged in 2021-08, with the labels that each got.

#6801 Création de 2021-08-05-dev-.python.-.fabrique.numerique.defense.sgdsn dans Fiche de poste !
  content/_jobs/2021-08-05-dev-.python.-.fabrique.numerique.defense.sgdsn.md
Labels: netlify-cms/pending_review

#6802 Création de 2021-08-05-dev-.svelte.tachyons dans Fiche de poste !
  content/_jobs/2021-08-05-dev-.svelte.tachyon.md
Labels: netlify-cms/pending_review

#6770 Création de 2021-07-30-potentiel.recrute.un.e.developpeur.se.fullstack dans Fiche de poste !
  content/_jobs/2021-07-30-potentiel.recrute.un.e.developpeur.se.fullstack.md
Labels: netlify-cms/draft

#6752 Création de 2021-07-29-lead.devops dans Fiche de poste !
  content/_jobs/2021-07-29-lead.devops.md
Labels: netlify-cms/draft

#6768 Création de 2021-07-30-potentiel.recrute.un.e.charge-e.de.deploiement dans Fiche de poste !
  content/_jobs/2021-07-30-potentiel.recrute.un.e.charge-e.de.deploiement.md
Labels: netlify-cms/draft

#6769 Création de 2021-07-30-potentiel.recrute dans Fiche de poste !
  content/_jobs/2021-07-30-potentiel.recrute.md
Labels: netlify-cms/draft

#6807 Création de cassiopee dans Produit !
  content/_startups/cassiopee.md
Labels: netlify-cms/pending_review

#6817 Mise à jour de 2021-06-17-charge-e.de.deploiement dans Fiche de poste
  content/_jobs/2021-06-17-charge-e.de.deploiement.md
Labels: netlify-cms/pending_publish

#6816 Création de octopus dans Produit !
  content/_startups/octopus.md
Labels: netlify-cms/pending_review

#6818 Mise à jour de usine-chatbots dans Produit
  content/_startups/usine-chatbots.md
  img/netlifycms/fabrique-chatbots.1.jpg
Labels: netlify-cms/pending_review

#6819 Mise à jour de usine-chatbots dans Produit
  content/_startups/usine-chatbots.md
Labels: netlify-cms/pending_review

#6821 Mise à jour de celia.corsin dans Membre
  content/_authors/celia.corsin.md
Labels: netlify-cms/pending_review

#6822 Mise à jour de camille.boulouis dans Membre
  content/_authors/camille.boulouis.md
Labels: netlify-cms/pending_review

#6820 Mise à jour de linna.taing dans Membre
  content/_authors/linna.taing.md
Labels: netlify-cms/pending_review

#6823 Mise à jour de romain.perroud dans Membre
  content/_authors/romain.perroud.md
Labels: netlify-cms/pending_review

#6809 Mise à jour de l-immersion-facile dans Produit
  content/_startups/l-immersion-facile.md
Labels: netlify-cms/pending_publish

#6832 Mise à jour de louis.anelli dans Membre
  content/_authors/louis.anelli.md
Labels: netlify-cms/draft

#6849 Mise à jour de arthur.hatchuel dans Membre
  content/_authors/arthur.hatchuel.md
Labels: netlify-cms/pending_publish

#6850 Mise à jour de thomas.eskenazi dans Membre
  content/_authors/thomas.eskenazi.md
Labels: netlify-cms/draft

#6859 Mise à jour de 2021-07-14-recrutement-mobilic-dev dans Fiche de poste
  content/_jobs/2021-07-14-recrutement-mobilic-dev.md
Labels: netlify-cms/draft

#6824 Mise à jour de thomas.glatt dans Membre
  content/_authors/thomas.glatt.md
Labels: netlify-cms/draft

#6793 Création de 2021-08-04-developpeuse.eur.full-stack dans Fiche de poste !
  content/_jobs/2021-08-04-developpeuse.eur.full-stack.md
Labels: netlify-cms/pending_review

#6888 Mise à jour de 2021-06-17-charge-e.de.deploiement dans Fiche de poste
  content/_jobs/2021-06-17-charge-e.de.deploiement.md
Labels: netlify-cms/pending_publish

#6917 Mise à jour de pauline.gourlet dans Membre
  content/_authors/pauline.gourlet.md
Labels: netlify-cms/pending_publish

#6922 Mise à jour de 2021-07-08-dev.javascript.ruby.confirme.ou.senior.pour.la.startup.mon.suivi.justice dans Fiche de poste
  content/_jobs/2021-07-08-dev.javascript.ruby.confirme.ou.senior.pour.la.startup.mon.suivi.justice.md
Labels: netlify-cms/draft

#6912 Mise à jour de 2021-07-21-developpeur.ou.developpeuse.fullstack dans Fiche de poste
  content/_jobs/2021-07-21-developpeur.ou.developpeuse.fullstack.md
Labels: netlify-cms/draft

#6937 Mise à jour de raphael.odini dans Membre
  content/_authors/raphael.odini.md
Labels: netlify-cms/pending_review
