Repository betagouv/beta.gouv.fr, pull requests merged in 2021-04, with the labels that each got.

#5512 Création de a-just dans Produit !
  content/_startups/a-just.md
Labels: netlify-cms/draft

#5531 Mise à jour de paul.marcade dans Membre
  content/_authors/paul.marcade.md
Labels: netlify-cms/draft

#5532 Mise à jour de aurelie.pretat dans Membre
  content/_authors/aurelie.pretat.md
Labels: netlify-cms/draft

#5533 Création de article.40 dans Produit !
  content/_startups/article.40.md
Labels: netlify-cms/draft

#5538 Mise à jour de morgan.izquierdo dans Membre
  content/_authors/morgan.izquierdo.md
Labels: netlify-cms/draft

#5539 Mise à jour de caroline-lucile.didier dans Membre
  content/_authors/caroline-lucile.didier.md
Labels: netlify-cms/draft

#5542 Mise à jour de jonathan.louis dans Membre
  content/_authors/jonathan.louis.md
Labels: netlify-cms/draft

#5543 Mise à jour de caroline-lucile.didier dans Membre
  content/_authors/caroline-lucile.didier.md
Labels: netlify-cms/draft

#5544 Mise à jour de caroline-lucile.didier dans Membre
  content/_authors/caroline-lucile.didier.md
Labels: netlify-cms/draft

#5556 Mise à jour de delphine.deneubourg dans Membre
  content/_authors/delphine.deneubourg.md
Labels: netlify-cms/draft

#5561 Mise à jour de cedric.merouani dans Membre
  content/_authors/cedric.merouani.md
Labels: netlify-cms/draft

#5562 Mise à jour de pierre.peyretou dans Membre
  content/_authors/pierre.peyretou.md
Labels: netlify-cms/draft

#5565 Création de marie.ramon-dare dans Membre !
  content/_authors/marie.ramon-dare.md
Labels: netlify-cms/draft

#5575 Mise à jour de augustin.stephan dans Membre
  content/_authors/augustin.stephan.md
Labels: netlify-cms/draft

#5590 Mise à jour de tristram.grabener dans Membre
  content/_authors/tristram.grabener.md
Labels: netlify-cms/draft

#5594 Mise à jour de tumeplay dans Produit
  content/_startups/tumeplay.md
Labels: netlify-cms/draft

#5596 Création de docurba dans Produit !
  content/_authors/adrien.laville.md
  content/_authors/hermance.gauthier.md
  content/_startups/docurba.md
Labels: netlify-cms/draft

#5613 Création de atlas.des.paysages dans Produit !
  content/_authors/livio.lumbroso.md
  content/_startups/atlas-des-paysages.md
Labels: netlify-cms/draft

#5612 Création de hydrogene dans Produit !
  content/_authors/livio.lumbroso.md
  content/_startups/hydrogene.md
Labels: netlify-cms/draft

#5605 Update jonathan.bourguignon.md
  content/_authors/jonathan.bourguignon.md
Labels: merge it !

#5616 Change date de départ
  content/_authors/juliette.palumbo.md
Labels: merge it !

#5611 Update yannick.francois.md
  content/_authors/yannick.francois.md
Labels: merge it !

#5633 Création de guichet-entreprises-nc dans Produit !
  content/_startups/guichet-entreprises-nc.md
  img/netlifycms/capture.2.png
  img/netlifycms/capture.3.png
  img/netlifycms/capture.png
Labels: netlify-cms/draft

#5634 Mise à jour de guichet-entreprises-nc dans Produit
  content/_startups/guichet-entreprises-nc.md
Labels: netlify-cms/draft

#5635 Mise à jour de guichet-entreprises-nc dans Produit
  content/_startups/guichet-entreprises-nc.md
Labels: netlify-cms/draft

#5636 Mise à jour de guichet-entreprises-nc dans Produit
  content/_startups/guichet-entreprises-nc.md
Labels: netlify-cms/draft

#5637 Mise à jour de guichet-entreprises-nc dans Produit
  content/_startups/guichet-entreprises-nc.md
Labels: netlify-cms/draft

#5638 Création de nc.connect dans Produit !
  content/_startups/nc.connect.md
Labels: netlify-cms/draft

#5650 Fix config.yml open_authoring
  admin/config.yml
Labels: merge it !

#5652 Update camille.garrigue.md
  content/_authors/camille.garrigue.md
Labels: merge it !

#5657 Update valentino.suma.md
  content/_authors/valentino.suma.md
Labels: merge it !

#5658 Mise à jour de matthieu.bollot dans Membre
  content/_authors/matthieu.bollot.md
Labels: netlify-cms/draft

#5672 Mise à jour de lucas.charrier dans Membre
  content/_authors/lucas.charrier.md
Labels: merge it !

#5677 Mise à jour de baptiste.ntsama dans Membre
  content/_authors/baptiste.ntsama.md
Labels: netlify-cms/draft

#5678 Mise à jour de karine.delforge dans Membre
  content/_authors/karine.delforge.md
Labels: netlify-cms/draft

#5679 Mise à jour de renaud.pons dans Membre
  content/_authors/renaud.pons.md
Labels: netlify-cms/draft

#5684 Update jerome.desboeufs.md (date de fin)
  content/_authors/jerome.desboeufs.md
Labels: merge it !

#5690 Mise à jour de florence.levy dans Membre
  content/_authors/florence.levy.md
Labels: merge it !, netlify-cms/draft

#5691 Update nassim.merzouk.md
  content/_authors/nassim.merzouk.md
Labels: merge it !

#5708 santepsy: dev recruitment to off
  content/_jobs/2021-03-30-sante-psy-dev.md
Labels: merge it !

#5699 Offre fermée - recrutement ok
  content/_jobs/2020-09-11-intrapreneur(se)_ANSSI.md
Labels: merge it !

#5700 Offre fermée - recrutement ok : 2020-09-10-coach_UX_innovation.md
  content/_jobs/2020-09-10-coach_UX_innovation.md
Labels: merge it !

#5692 Prolongation Franck Signaux Faibles
  content/_authors/franck.coufourier.md
Labels: merge it !

#5712 Update lbb authors
  content/_authors/alexandre.cantin.md
  content/_authors/anne.pichon.md
  content/_authors/regis.behmo.md
Labels: merge it !

#5664 Ajout d'image via upload pour NC Connect
  img/startups/nc.connect.png
Labels: merge it !

#5717 Create a job offer for Etalab
  content/_jobs/2021-04-21-dev-piaf.md
Labels: merge it !

#5709 raccourcit la description courte de l'incubateur
  content/_incubators/mission-apprentissage.md
Labels: merge it !

#5736 Mise à jour de florian.briand dans Membre
  content/_authors/florian.briand.md
Labels: netlify-cms/draft

#5733 Update raphael.pierquin.md
  content/_authors/raphael.pierquin.md
Labels: merge it !

#5734 Création de developpeur.ou.developpeur.full.stack dans Fiche de poste !
  content/_jobs/developpeur.ou.developpeur.full.stack.md
Labels: netlify-cms/draft

#5729 New job offer for Etalab (Piaf project)
  content/_jobs/2021-04-22-datascience-piaf.md
Labels: merge it !

#5744 Update jean-michel.armand.md
  content/_authors/jean-michel.armand.md
Labels: merge it !

#5722 Amélioration message de template de PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: merge it !

#5721 Ajout de Secretariat dans le readme
  README.md
Labels: merge it !

#5765 Supprime les tabs sur /communaute
  _layouts/annuaire.html
  _layouts/communaute.html
  _plugins/community.rb
Labels: merge it !

#5763 wording
  content/_jobs/2021-04-21-dev-piaf.md
Labels: merge it !

#5730 typo
  content/_jobs/2021-04-21-dev-piaf.md
Labels: merge it !

#5674 Fixed singular title when counter <= 1
  _layouts/startups.html
  assets/additional/js/search-startup.js
Labels: merge it !

#5770 Update fast.md
  _pages/programme/fast.md
Labels: merge it !

#5768 Fin de mission
  content/_authors/jerome.rivals.md
Labels: merge it !

#5776 Fix bio in Netlfiy CMS
  admin/config.yml
Labels: merge it !

#5777 Fix domaine
  content/_authors/jeremie.cook.md
  content/_authors/julien.dauphant.md
  rb/schema/authors.yml
Labels: merge it !

#5784 Delete apprentissage.md
  content/_startups/apprentissage.md
Labels: merge it !

#5797 Création de ideaule.informations.sur.les.dossiers.et.les.actes.uniques.loi.sur.l.eau dans Produit !
  content/_startups/ideaule.informations.sur.les.dossiers.et.les.actes.uniques.loi.sur.l.eau.md
Labels: netlify-cms/draft

#5799 Rename classes12.md to classe-a-12.md
  content/_authors/aymeric.faivre.md
  content/_authors/jean-philippe.poisson.md
  content/_authors/jeremie.cook.md
  content/_authors/malika.alouani.md
  content/_authors/mathieu.agopian.md
  content/_authors/nicolas.leyri.md
  content/_authors/vincent.agnano.md
  content/_authors/yohan.boniface.md
  content/_jobs/2018-08-29-classes12-dev.md
  content/_startups/classe-a-12.md
Labels: merge it !

#5779 Mise à jour de theophile.merliere dans Membre
  content/_authors/theophile.merliere.md
Labels: merge it !, netlify-cms/draft

#5788 Update alameen.abdul-khudoos.md
  content/_authors/alameen.abdul-khudoos.md
Labels: merge it !

#5802 Mise à jour de ideaule.informations.sur.les.dossiers.et.les.actes.uniques.loi.sur.l.eau dans Produit
  content/_startups/ideaule.md
Labels: merge it !, netlify-cms/draft

#5803 Fix role (qui doit être migré à description dans un futur proche)
  admin/config.yml
Labels: merge it !

#5804 Mise à jour de ideaule dans Produit
  content/_startups/ideaule.md
Labels: merge it !, netlify-cms/pending_review
