Repository betagouv/beta.gouv.fr, pull requests merged in 2021-03, with the labels that each got.

#5356 Mise à jour de alexandre.grimault dans Membre
  content/_authors/alexandre.grimault.md
Labels: netlify-cms/draft

#4613 Update romy.duhem-verdiere.md
  content/_authors/romy.duhem-verdiere.md
Labels: modifications nécessaires

#5303 Marievanhaecke investigation
  content/_startups/tutorat_fp.md
Labels: En discussion

#5377 Mise à jour de tumeplay dans Produit
  content/_startups/tumeplay.md
Labels: netlify-cms/draft

#5404 Mise à jour de marie.vanhaecke dans Membre
  content/_authors/marie.vanhaecke.md
Labels: netlify-cms/draft

#5380 Mise à jour de rdv.consulat dans Produit
  content/_startups/rdv.consulat.md
Labels: netlify-cms/draft

#5405 Update thomas.bouchardon.md
  content/_authors/thomas.bouchardon.md
Labels: merge it !

#5414 Update herve.cauwelier.md
  content/_authors/herve.cauwelier.md
Labels: merge it !

#5321 Améliore l'affichage des liens hypertexte.
  content/_jobs/2020-11-12-offre-designer-e-inspé.md
Labels: merge it !

#5410 Update damien.boyer.md
  content/_authors/damien.boyer.md
Labels: merge it !

#5407 Update vincent.laine.md
  content/_authors/vincent.laine.md
Labels: merge it !

#5416 Update paul.burgun.md
  content/_authors/paul.burgun.md
Labels: merge it !

#5412 Mise à jour de 1000.jours dans Produit
  content/_startups/1000.jours.md
Labels: En discussion, netlify-cms/draft

#5428 Création de latelier.numerique.du.ministere.de.leurope.et.des.affaires.etrangeres dans Incubateur !
  content/_incubators/latelier.numerique.du.ministere.de.leurope.et.des.affaires.etrangeres.md
Labels: netlify-cms/draft

#5429 Mise à jour de beatrice.mercier dans Membre
  content/_authors/beatrice.mercier.md
Labels: netlify-cms/draft

#5436 Création de aides.jeunes dans Produit !
  content/_startups/aides.jeunes.md
Labels: netlify-cms/draft

#5437 Création de talents.numeriques dans Produit !
  content/_startups/talents-numeriques.md
Labels: netlify-cms/draft

#5484 Mise à jour de adrien.laville dans Membre
  content/_authors/adrien.laville.md
Labels: netlify-cms/draft

#5498 Mise à jour de victoria.martinez dans Membre
  content/_authors/victoria.martinez.md
Labels: netlify-cms/draft

#5499 Mise à jour de perrine.garnault dans Membre
  content/_authors/perrine.garnault.md
Labels: netlify-cms/draft

#5501 Mise à jour de yassine.riffi dans Membre
  content/_authors/yassine.riffi.md
Labels: netlify-cms/draft

#5502 Mise à jour de saniya.al_saadi dans Membre
  content/_authors/saniya.al_saadi.md
Labels: netlify-cms/draft

#5505 Mise à jour de saniya.al_saadi dans Membre
  content/_authors/saniya.al_saadi.md
Labels: netlify-cms/draft

#5506 Mise à jour de pierre-olivier.mauguet dans Membre
  content/_authors/pierre-olivier.mauguet.md
Labels: netlify-cms/draft

#5474 Mise à jour startups
  content/_authors/julien.dauphant.md
Labels: merge it !

#5517 Mise à jour de paul.leclercq dans Membre
  content/_authors/paul.leclercq.md
Labels: merge it !, netlify-cms/draft

#5514 Mise à jour de chèquespsy dans Produit
  content/_startups/chèquespsy.md
Labels: netlify-cms/draft

#5515 Mise à jour de estelle.comment dans Membre
  content/_authors/estelle.comment.md
Labels: netlify-cms/draft

#5516 Mise à jour de emeline.merliere dans Membre
  content/_authors/emeline.merliere.md
Labels: netlify-cms/draft

#5445 Contact est obligatoire dans les fiches startup
  admin/config.yml
Labels: merge it !

#5527 Changement date de fin
  content/_authors/vincent.lara.md
Labels: merge it !
