Repository betagouv/beta.gouv.fr, pull requests merged in 2021-07, with the labels that each got.

#6425 Mise à jour de 2021-06-17-charge-e.de.deploiement dans Fiche de poste
  content/_jobs/2021-06-17-charge-e.de.deploiement.md
Labels: netlify-cms/draft

#6447 Création de 2021-07-05-administrateur.trice.systeme.senior dans Fiche de poste !
  content/_jobs/2021-07-05-administrateur.trice.systeme.senior.md
Labels: netlify-cms/pending_publish

#6453 Mise à jour de resorption-bidonvilles dans Produit
  content/_startups/resorption-bidonvilles.md
Labels: netlify-cms/draft

#6454 Create 2021-07-06-place-de-marche-inclusion-dev-dango.md
  content/_jobs/2021-07-06-place-de-marche-inclusion-dev-dango.md
Labels: merge it !

#6464 Création de reva dans Produit !
  content/_authors/david.massiani.md
  content/_authors/florian.briand.md
  content/_authors/marie.briche.md
  content/_authors/olivier.gerard.md
  content/_authors/ophelie.lamarque.md
  content/_authors/paquita.frances.md
  content/_authors/philippe.petitqueux.md
  content/_authors/veronique.lacoma.md
  content/_jobs/2021-06-24-dev-reva.md
  content/_startups/reva.md
Labels: netlify-cms/pending_review

#6469 Mise à jour de inca dans Produit
  content/_startups/inca.md
Labels: netlify-cms/draft

#6480 Création de 2021-07-07-designer.ux.ui dans Fiche de poste !
  content/_jobs/2021-07-07-designer.ux.ui.md
Labels: netlify-cms/draft

#6481 Création de 2021-07-07-developpeur.euse.fullstack dans Fiche de poste !
  content/_jobs/2021-07-07-developpeur.euse.fullstack.md
Labels: netlify-cms/draft

#6483 Mise à jour de 2021-06-10-charge-e.de.laffectation.du.suivi.de.signalements.et.animation.de.territoire dans Fiche de poste
  content/_jobs/2021-06-10-charge-e.de.laffectation.du.suivi.de.signalements.et.animation.de.territoire.md
Labels: netlify-cms/draft

#6490 Mise à jour de 2021-07-05-camino-beta-gouv-fr.recrute.un.developpeur.se.full.stack dans Fiche de poste
  content/_jobs/2021-07-05-camino-beta-gouv-fr.recrute.un.developpeur.se.full.stack.md
Labels: netlify-cms/draft

#6492 Création de 2021-07-09-la.mission.interministerielle.pour.l.apprentissage.recrute.un.e.charge-e.de.deploiement.des.produits.aupres.des.cfa dans Fiche de poste !
  content/_jobs/mia_déploiementcfa.md
Labels: netlify-cms/draft

#6501 Création de 2021-07-09-un.ou.une.responsable.produit.numerique dans Fiche de poste !
  content/_jobs/2021-07-09-un.ou.une.responsable.produit.numerique.md
Labels: netlify-cms/draft

#6502 Création de 2021-07-09-developpeur.ou.developpeuse dans Fiche de poste !
  content/_jobs/2021-07-09-developpeur.ou.developpeuse.md
Labels: netlify-cms/draft

#6505 Mise à jour de 2021-07-09-developpeur.ou.developpeuse dans Fiche de poste
  content/_jobs/2021-07-09-developpeur.ou.developpeuse.md
Labels: netlify-cms/draft

#6506 Mise à jour de 2021-07-09-un.ou.une.responsable.produit.numerique dans Fiche de poste
  content/_jobs/2021-07-09-un.ou.une.responsable.produit.numerique.md
Labels: netlify-cms/draft

#6470 Mise à jour de urgencevie dans Produit
  content/_startups/urgencevie.md
Labels: netlify-cms/draft

#6504 Mise à jour de justif dans Produit
  content/_startups/justif.md
Labels: netlify-cms/draft

#6532 Mise à jour de gaspard.granger dans Membre
  content/_authors/gaspard.granger.md
Labels: netlify-cms/draft

#6533 Mise à jour de benoit.morane dans Membre
  content/_authors/benoit.morane.md
Labels: netlify-cms/draft

#6534 Mise à jour de claire.vigier dans Membre
  content/_authors/claire.vigier.md
Labels: netlify-cms/draft

#6537 Mise à jour de 2021-06-25-covoitdeploiement dans Fiche de poste
  content/_jobs/2021-06-25-covoitdeploiement.md
Labels: netlify-cms/draft

#6607 Création de limmersion.facile dans Produit !
  content/_startups/limmersion.facile.md
Labels: netlify-cms/pending_publish

#6625 Création de 2021-07-19-un.e.developpeur.euse.fullstack dans Fiche de poste !
  content/_jobs/2021-07-19-un.e.developpeur.euse.fullstack.md
Labels: netlify-cms/draft

#6628 Mise à jour de 2021-07-07-designer.ux.ui dans Fiche de poste
  content/_jobs/2021-07-07-designer.ux.ui.md
Labels: netlify-cms/draft

#6629 Mise à jour de nicolas.enjalbert dans Membre
  content/_authors/nicolas.enjalbert.md
Labels: netlify-cms/draft

#6631 Mise à jour de atlas-des-paysages dans Produit
  content/_startups/atlas-des-paysages.md
Labels: netlify-cms/pending_publish

#6640 Création de 2021-07-21-developpeur.ou.developpeuse.fullstack dans Fiche de poste !
  content/_jobs/2021-07-21-developpeur.ou.developpeuse.fullstack.md
Labels: netlify-cms/draft

#6671 Mise à jour de hydrogene dans Produit
  content/_startups/hydrogene.md
Labels: netlify-cms/pending_publish

#6632 Création de wikicarbone dans Produit !
  content/_startups/wikicarbone.md
Labels: netlify-cms/draft

#6672 Mise à jour de emilie.fleury-jagerschmidt dans Membre
  content/_authors/emilie.fleury-jagerschmidt.md
Labels: netlify-cms/pending_publish

#6673 Mise à jour de lionel.prevors dans Membre
  content/_authors/lionel.prevors.md
Labels: netlify-cms/pending_publish

#6674 Mise à jour de julie.benzoni dans Membre
  content/_authors/julie.benzoni.md
Labels: netlify-cms/pending_publish

#6675 Mise à jour de wikicarbone dans Produit
  content/_startups/wikicarbone.md
Labels: netlify-cms/pending_publish

#6676 Mise à jour de nicolas.perriault dans Membre
  content/_authors/nicolas.perriault.md
Labels: netlify-cms/pending_publish

#6677 Mise à jour de livio.lumbroso dans Membre
  content/_authors/livio.lumbroso.md
Labels: netlify-cms/pending_publish

#6678 Mise à jour de pascal.dagras dans Membre
  content/_authors/pascal.dagras.md
Labels: netlify-cms/pending_publish

#6689 Mise à jour de 2021-06-21-immersion-facile-dev dans Fiche de poste
  content/_jobs/2021-06-21-immersion-facile-dev.md
Labels: netlify-cms/pending_publish

#6693 Mise à jour de 2021-07-09-developpeur.ou.developpeuse dans Fiche de poste
  content/_jobs/2021-07-09-developpeur.ou.developpeuse.md
Labels: netlify-cms/draft

#6694 Mise à jour de 2021-07-09-un.ou.une.responsable.produit.numerique dans Fiche de poste
  content/_jobs/2021-07-09-un.ou.une.responsable.produit.numerique.md
Labels: netlify-cms/draft

#6695 Mise à jour de 2021-05-28-charge.de.deploiement.business.developper.pour.mon.suivi.justice dans Fiche de poste
  content/_jobs/2021-05-28-charge.de.deploiement.business.developper.pour.mon.suivi.justice.md
Labels: netlify-cms/draft

#6707 Mise à jour de anne-sophie.tranchet dans Membre
  content/_authors/anne-sophie.tranchet.md
Labels: netlify-cms/pending_publish

#6709 Mise à jour de 2021-07-27-un.ou.une.designer.ux.ui dans Fiche de poste
  content/_jobs/2021-07-27-un.ou.une.designer.ux.ui.md
Labels: netlify-cms/draft

#6710 Mise à jour de 2021-07-27-un.ou.une.designer.ux.ui dans Fiche de poste
  content/_jobs/2021-07-27-un.ou.une.designer.ux.ui.md
Labels: netlify-cms/pending_publish

#6711 Mise à jour de 2021-07-27-un.ou.une.designer.ux.ui dans Fiche de poste
  content/_jobs/2021-07-27-un.ou.une.designer.ux.ui.md
Labels: netlify-cms/pending_publish

#6724 Mise à jour de maxine.sabater dans Membre
  content/_authors/maxine.sabater.md
Labels: netlify-cms/draft

#6736 Mise à jour de clara.lanthiez dans Membre
  content/_authors/clara.lanthiez.md
Labels: netlify-cms/pending_review

#6751 Mise à jour de ronan.james dans Membre
  content/_authors/ronan.james.md
Labels: netlify-cms/draft

#6765 Mise à jour de jonathan.louis dans Membre
  content/_authors/jonathan.louis.md
Labels: netlify-cms/draft
