Repository betagouv/beta.gouv.fr, pull requests merged in 2021-05, with the labels that each got.

#5807 Corrige le slug des fiches de job et désactive le bouton de publication
  admin/config.yml
  admin/index.html
Labels: merge it !

#5820 Création de 2021-05-03-charge.ou.chargee.de.deploiement dans Fiche de poste !
  content/_jobs/2021-05-03-charge.ou.chargee.de.deploiement.md
Labels: netlify-cms/draft

#5830 Mise à jour de 2021-05-03-charge.ou.chargee.de.deploiement dans Fiche de poste
  content/_jobs/2021-05-03-charge.ou.chargee.de.deploiement.md
Labels: netlify-cms/draft

#5851 Création de 2021-05-04-charge.ou.chargee.de.deploiement.psychologues dans Fiche de poste !
  content/_jobs/2021-05-04-charge.ou.chargee.de.deploiement.psychologues.md
Labels: netlify-cms/draft

#5836 Add files via upload
  content/_jobs/2021-05-04-mobilic-recrute-un-e-business-developer.md
Labels: merge it !

#5837 Update 2021-05-04-developpeur-startup-estime.md
  content/_jobs/2021-05-04-developpeur-startup-estime.md
Labels: merge it !

#5805 Domaine ministeriel obligatoire dans netlifly comme dans la CI
  admin/config.yml
Labels: merge it !

#5854 Correction de la mission de devoirs-faits-communauté
  content/_startups/devoirs-faits-communaute.md
Labels: merge it !

#5743 Mise à jour de justif dans Produit
  content/_startups/justif.md
Labels: merge it !

#5857 Mise à jour de justif dans Produit
  content/_startups/justif.md
Labels: netlify-cms/draft

#5859 Mise à jour de lery.jicquel dans Membre
  content/_authors/lery.jicquel.md
Labels: netlify-cms/draft

#5791 Update and rename mission-apprentissage.md to mission-interministérie…
  content/_incubators/mission-apprentissage.md
  content/_startups/catalogue-apprentissage.md
  content/_startups/catalogue.des.formations.en.apprentissage.md
  content/_startups/la-bonne-alternance.md
  content/_startups/rdv.apprentissage.md
Labels: merge it !

#5806 Contrainte de 20 caractères pour les noms de startup dans netlify
  admin/config.yml
Labels: merge it !

#5871 Mise à jour de investigation.carnet.de.bord dans Produit
  content/_startups/investigation.carnet.de.bord.md
Labels: netlify-cms/draft

#5878 Mise à jour de investigation.offre.dinsertion dans Produit
  content/_startups/investigation.offre.dinsertion.md
Labels: netlify-cms/draft

#5880 Mise à jour de anne.pichon dans Membre
  content/_authors/anne.pichon.md
Labels: netlify-cms/draft

#5881 Mise à jour de investigation.offre.dinsertion dans Produit
  content/_startups/investigation.offre.dinsertion.md
Labels: netlify-cms/draft

#5882 Mise à jour de investigation.offre.dinsertion dans Produit
  content/_startups/investigation.offre.dinsertion.md
Labels: netlify-cms/draft

#5910 Mise à jour de au-compost-mitoyen dans Produit
  content/_startups/au-compost-mitoyen.md
Labels: netlify-cms/draft

#5865 Update nathalie.reyre.md
  content/_authors/nathalie.reyre.md
Labels: merge it !

#5870 Mise à jour de tutorat_fp dans Produit
  content/_startups/tutorat_fp.md
Labels: netlify-cms/draft

#5886 Update etienne.pichot-damon.md
  content/_authors/etienne.pichot-damon.md
Labels: merge it !

#5923 Mise à jour de florian.corgnou dans Membre
  content/_authors/florian.corgnou.md
Labels: netlify-cms/draft

#5925 Mise à jour de gael.destrem dans Membre
  content/_authors/gael.destrem.md
Labels: netlify-cms/draft

#5931 Création de 2021-05-12-des.developpeuses.et.developpeurs.seniors.pour.les.startups.detat.du.ministere.de.la.transition.ecologique dans Fiche de poste !
  content/_jobs/2021-05-12-des.developpeuses.et.developpeurs.seniors.pour.les.startups.detat.du.ministere.de.la.transition.ecologique.md
Labels: merge it !, netlify-cms/draft

#5933 Mise à jour de marvin.cabanais dans Membre
  content/_authors/marvin.cabanais.md
Labels: merge it !, netlify-cms/draft

#5940 Mise à jour de charlotte.lecuit dans Membre
  content/_authors/charlotte.lecuit.md
Labels: netlify-cms/draft

#5941 Rename marvin.cabanais.md to marvin.cabannais.md
  content/_authors/marvin.cabannais.md
Labels: merge it !

#5946 Mise à jour de michael.latour dans Membre
  content/_authors/michael.latour.md
Labels: netlify-cms/draft

#5884 Update justif.md
  content/_startups/justif.md
Labels: merge it !

#5951 Mise à jour de 2021-05-12-des.developpeuses.et.developpeurs.seniors.pour.les.startups.detat.du.ministere.de.la.transition.ecologique dans Fiche de poste
  content/_jobs/2021-05-12-des.developpeuses.et.developpeurs.seniors.pour.les.startups.detat.du.ministere.de.la.transition.ecologique.md
Labels: netlify-cms/draft

#5973 Update christophe.trouillard.md
  content/_authors/christophe.trouillard.md
Labels: merge it !

#5893 job closed
  content/_jobs/2021-04-21-dev-piaf.md
Labels: merge it !

#5866 Mise à jour de adrien.plantureux dans Membre
  content/_authors/adrien.plantureux.md
Labels: merge it !, netlify-cms/draft

#5976 Mise à jour de paul-henri.charrier dans Membre
  content/_authors/paul-henri.charrier.md
Labels: netlify-cms/draft

#5977 Mise à jour de victor.grange dans Membre
  content/_authors/victor.grange.md
Labels: netlify-cms/draft

#5978 Mise à jour de lery.jicquel dans Membre
  content/_authors/lery.jicquel.md
Labels: netlify-cms/draft

#5979 Création de 2021-05-14-acceslibre.recrute.un.e.lead.developpeur.euse dans Fiche de poste !
  content/_jobs/2021-05-14-acceslibre.recrute.un.e.lead.developpeur.euse.md
Labels: netlify-cms/draft

#5981 Update soumia.ahlouch.md
  content/_authors/soumia.ahlouch.md
Labels: merge it !

#5982 Suppression compte Github suspect
  content/_authors/laurent.charpentier.md
Labels: merge it !

#5984 Add button to manual sync
  .github/workflows/sync-authors-to-blog.yml
Labels: merge it !

#5986 Mise à jour API csv
  api/v2.1/authors.csv
Labels: merge it !

#5991 Update livio.lumbroso.md
  content/_authors/livio.lumbroso.md
Labels: merge it !

#5987 Update clement.biron.md
  content/_authors/clement.biron.md
Labels: merge it !

#5999 Mise à jour de pierre-olivier.mauguet dans Membre
  content/_authors/pierre-olivier.mauguet.md
Labels: netlify-cms/draft

#6009 Update christophe.bonraisin.md
  content/_authors/christophe.bonraisin.md
Labels: merge it !

#6003 Update 2021-04-16-covoiturage-dev.md
  content/_jobs/2021-04-16-covoiturage-dev.md
Labels: merge it !

#6012 Fermeture du poste chargé(e) de déploiement
  content/_jobs/2021-01-08-resorption-bidonvilles-bizdev.md
Labels: merge it !

#5990 Update lydia.sanaa.md
  content/_authors/lydia.sanaa.md
Labels: merge it !

#6023 Mise à jour de dumas dans Produit
  content/_startups/dumas.md
Labels: netlify-cms/draft

#6026 Mise à jour de lery.jicquel dans Membre
  content/_authors/lery.jicquel.md
Labels: netlify-cms/draft

#6028 Mise à jour de christophe.trouillard dans Membre
  content/_authors/christophe.trouillard.md
Labels: netlify-cms/draft

#6029 Mise à jour de julien.kounowski dans Membre
  content/_authors/julien.kounowski.md
Labels: netlify-cms/draft

#6020 we found our candidate so we close this job offer
  content/_jobs/2021-04-22-datascience-piaf.md
Labels: merge it !

#6016 Mise à jour de talents-numeriques dans Produit
  content/_startups/talents-numeriques.md
Labels: netlify-cms/draft

#6037 Mise à jour de talents-numeriques dans Produit
  content/_startups/talents-numeriques.md
Labels: netlify-cms/draft

#6013 Change la limite du nombre de caractères 20 -> 30
  admin/config.yml
Labels: merge it !

#6045 Update yesmine.benlarbi.md
  content/_authors/yesmine.benlarbi.md
Labels: merge it !

#6030 Update raphael.marvie.md
  content/_authors/raphael.marvie.md
Labels: merge it !

#6001 Mise à jour de engagement-civique dans Produit
  content/_startups/engagement-civique.md
Labels: merge it !, netlify-cms/draft

#6050 Création de 2021-05-25-mon-entreprise-fr.recrute.js dans Fiche de poste !
  content/_jobs/2021-05-25-mon-entreprise-fr.recrute.js.md
Labels: netlify-cms/pending_review

#6075 Mise à jour de investigation.offre.dinsertion dans Produit
  content/_startups/investigation.offre.dinsertion.md
Labels: netlify-cms/draft

#6079 Création de 2021-05-27-developpeur.se.full.stack.-.python.django dans Fiche de poste !
  content/_jobs/2021-05-27-developpeur.se.full.stack.-.python.django.md
Labels: netlify-cms/draft

#6083 Mise à jour de patrick.lambret dans Membre
  content/_authors/patrick.lambret.md
Labels: netlify-cms/draft

#6086 Mise à jour de arnaud.denoix dans Membre
  content/_authors/arnaud.denoix.md
Labels: netlify-cms/draft

#6085 Mise à jour de agathe.latreille dans Membre
  content/_authors/agathe.latreille.md
Labels: netlify-cms/draft

#6034 Création de 2021-05-20-designer.ui.ux.freelance dans Fiche de poste !
  content/_jobs/2021-05-20-designer.ui.ux.freelance.md
Labels: netlify-cms/draft

#6069 Mise à jour de florian.derfurth dans Membre
  content/_authors/florian.derfurth.md
Labels: netlify-cms/draft

#6068 Mise à jour de fanny.cheung dans Membre
  content/_authors/fanny.cheung.md
Labels: netlify-cms/draft

#6067 Mise à jour de anne.poirot dans Membre
  content/_authors/anne.poirot.md
Labels: netlify-cms/draft

#6066 Mise à jour de maitane.lenoir dans Membre
  content/_authors/maitane.lenoir.md
Labels: netlify-cms/draft

#6102 Création de 2021-05-31-un-e.charge-e.de.produit dans Fiche de poste !
  content/_jobs/2021-05-31-un-e.charge-e.de.produit.md
Labels: netlify-cms/draft

#6089 Création de 2021-05-28-charge.de.deploiement.business.developper.pour…
  content/_jobs/2021-05-28-charge.de.deploiement.business.developper.pour.mon.suivi.justice.md
Labels: En discussion
