Repository betagouv/beta.gouv.fr, pull requests merged in 2021-11, with the labels that each got.

#7442 Mise à jour de laetitia.kouadria dans Membre
  content/_authors/laetitia.kouadria.md
Labels: netlify-cms/pending_review

#7443 Mise à jour de zero-logement-vacant dans Produit
  content/_startups/zero-logement-vacant.md
Labels: netlify-cms/draft

#7455 Mise à jour de data.insertion dans Produit
  content/_startups/data.insertion.md
Labels: netlify-cms/pending_review

#7456 Mise à jour de jerome.lenez dans Membre
  content/_authors/jerome.lenez.md
Labels: netlify-cms/pending_review

#7461 Création de 2021-11-03-un.e.charge.e.de.deploiement dans Fiche de poste !
  content/_jobs/2021-11-03-un.e.charge.e.de.deploiement.md
Labels: netlify-cms/pending_review

#7433 Création de solution.audiovisuelle.easi dans Produit !
  content/_startups/solution.audiovisuelle.easi.md
  img/netlifycms/pre.sentation.de.la.solution_easi_delphine.machet.png
Labels: netlify-cms/pending_review

#7429 Création de faritas dans Produit !
  content/_startups/faritas.md
  img/netlifycms/calendrier.de.re.alisation_faritas_laurent.malet.png
Labels: netlify-cms/pending_review

#7431 Création de candela dans Produit !
  content/_startups/candela.md
  img/netlifycms/pre.sentation.de.la.solution_candela_se.bastien.vanc.on.png
Labels: netlify-cms/pending_review

#7470 Mise à jour de caroline.delorme dans Membre
  content/_authors/caroline.delorme.md
Labels: netlify-cms/pending_review

#7471 Mise à jour de laurent.barbat dans Membre
  content/_authors/laurent.barbat.md
Labels: netlify-cms/pending_review

#7472 Mise à jour de mathieu.perez dans Membre
  content/_authors/mathieu.perez.md
Labels: netlify-cms/pending_review

#7473 Mise à jour de laurent.charpentier dans Membre
  content/_authors/laurent.charpentier.md
Labels: netlify-cms/pending_review

#7474 Mise à jour de maxine.sabater dans Membre
  content/_authors/maxine.sabater.md
Labels: netlify-cms/pending_review

#7475 Mise à jour de fabrique-dgfip dans Incubateur
  content/_incubators/fabrique-dgfip.md
Labels: netlify-cms/pending_review

#7427 Mise à jour de thomas.eskenazi dans Membre
  content/_authors/thomas.eskenazi.md
Labels: netlify-cms/pending_review

#7444 Mise à jour de maxime.teneur dans Membre
  content/_authors/maxime.teneur.md
Labels: netlify-cms/pending_review

#7476 Mise à jour de lionel.breduillieard dans Membre
  content/_authors/lionel.breduillieard.md
Labels: netlify-cms/draft

#7480 Mise à jour de laurent.malet dans Membre
  content/_authors/laurent.malet.md
Labels: netlify-cms/pending_review

#7489 Mise à jour de cecilia.tenet dans Membre
  content/_authors/cecilia.tenet.md
Labels: netlify-cms/draft

#7488 Mise à jour de delphine.machet dans Membre
  content/_authors/delphine.machet.md
Labels: netlify-cms/pending_review

#7487 Mise à jour de karel.cloarec dans Membre
  content/_authors/karel.cloarec.md
Labels: netlify-cms/draft

#7486 Mise à jour de sebastien.vancon dans Membre
  content/_authors/sebastien.vancon.md
Labels: netlify-cms/pending_review

#7485 Mise à jour de caroline.delorme dans Membre
  content/_authors/caroline.delorme.md
Labels: netlify-cms/pending_review

#7483 Mise à jour de margaux.nonclercq dans Membre
  content/_authors/margaux.nonclercq.md
Labels: netlify-cms/pending_review

#7496 Mise à jour de thierry.verrecchia dans Membre
  content/_authors/thierry.verrecchia.md
Labels: netlify-cms/pending_review

#7169 Mise à jour de 2021-02-15-engagement-civique-SNU-support-animation-referents dans Fiche de poste
  content/_jobs/2021-02-15-engagement-civique-SNU-support-animation-referents.md
Labels: netlify-cms/draft

#7504 Mise à jour de jonathan.louis dans Membre
  content/_authors/jonathan.louis.md
Labels: netlify-cms/pending_publish

#7503 Mise à jour de solution.audiovisuelle.easi dans Produit
  content/_startups/solution.audiovisuelle.easi.md
Labels: netlify-cms/pending_review

#7501 Mise à jour de faritas dans Produit
  content/_startups/faritas.md
  img/netlifycms/20211104_calendrier.de.re.alisation_faritas_laurent.malet.redimensionne.png
Labels: netlify-cms/pending_review

#7500 Mise à jour de attractivite.des.territoires dans Produit
  content/_startups/attractivite.des.territoires.md
  img/netlifycms/20211104_calendrier.de.re.alisation_attractivite.des.territoires_caroline.delorme.redimensionne.png
Labels: netlify-cms/pending_review

#7549 Mise à jour de alexis.kohl dans Membre
  content/_authors/alexis.kohl.md
Labels: netlify-cms/draft

#7557 Création de dialogue.operationnel dans Produit !
  content/_startups/dialogue.operationnel.md
Labels: netlify-cms/pending_review

#7558 Mise à jour de psij dans Produit
  content/_startups/psij.md
Labels: netlify-cms/draft

#7562 Mise à jour de cyril.cincet dans Membre
  content/_authors/cyril.cincet.md
Labels: netlify-cms/draft

#7563 Mise à jour de polex dans Produit
  content/_startups/polex.md
Labels: netlify-cms/draft

#7564 Mise à jour de stephane.ritter dans Membre
  content/_authors/stephane.ritter.md
Labels: netlify-cms/draft

#7565 Mise à jour de dominique.lequepeys dans Membre
  content/_authors/dominique.lequepeys.md
Labels: netlify-cms/draft

#7570 Mise à jour de valerie.lacroixdaniel dans Membre
  content/_authors/valerie.lacroixdaniel.md
Labels: netlify-cms/draft

#7568 Mise à jour de annaelle.desabres dans Membre
  content/_authors/annaelle.desabres.md
Labels: netlify-cms/draft

#7567 Mise à jour de adele.schlauder dans Membre
  content/_authors/adele.schlauder.md
Labels: netlify-cms/draft

#7569 Mise à jour de philippe.libat dans Membre
  content/_authors/philippe.libat.md
Labels: netlify-cms/pending_publish

#7572 Mise à jour de polex dans Produit
  content/_startups/polex.md
Labels: netlify-cms/draft

#7576 Mise à jour de stephane.ritter dans Membre
  content/_authors/stephane.ritter.md
Labels: netlify-cms/draft

#7604 Développeur backend Trackdéchets
  content/_jobs/2021-11-15-un.e.developpeur.se.backend.senior.md
Labels: netlify-cms/draft

#7623 Mise à jour de polex dans Produit
  content/_startups/polex.md
Labels: netlify-cms/draft

#7624 Mise à jour de 1000.jours dans Produit
  content/_startups/1000.jours.md
Labels: netlify-cms/draft

#7631 Création de 2021-11-17-charge.e.de.croissance dans Fiche de poste !
  content/_jobs/2021-11-17-charge.e.de.croissance.md
Labels: netlify-cms/pending_publish

#7634 Mise à jour de 2021-11-17-charge.e.de.croissance dans Fiche de poste
  content/_jobs/2021-11-17-charge.e.de.croissance.md
Labels: netlify-cms/draft

#7636 Mise à jour de 2021-11-17-charge.e.de.croissance dans Fiche de poste
  content/_jobs/2021-11-17-charge.e.de.croissance.md
Labels: netlify-cms/draft

#7640 Mise à jour de 2021-11-17-charge.e.de.croissance dans Fiche de poste
  content/_jobs/2021-11-17-charge.e.de.croissance.md
Labels: netlify-cms/draft

#7642 Mise à jour de 2021-11-17-charge.e.de.croissance dans Fiche de poste
  content/_jobs/2021-11-17-charge.e.de.croissance.md
Labels: netlify-cms/draft

#7643 Création de 2021-11-17-developpeur-se.experimente-e.ruby.full.stack dans Fiche de poste !
  .github/workflows/tests.yml
  content/_jobs/2021-11-17-developpeur-se.experimente-e.ruby.full.stack.md
Labels: netlify-cms/pending_publish

#7650 Mise à jour de dora dans Produit
  content/_startups/dora.md
Labels: netlify-cms/draft

#7648 Mise à jour de mano dans Produit
  content/_startups/mano.md
Labels: netlify-cms/draft

#7676 Mise à jour de carnet.de.bord dans Produit
  content/_startups/carnet.de.bord.md
Labels: netlify-cms/pending_publish

#7679 Création de 2021-11-19-dev.full.stack dans Fiche de poste !
  content/_jobs/2021-11-19-dev.full.stack.md
Labels: netlify-cms/pending_review

#7680 Création de 2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques dans Fiche de poste !
  content/_jobs/2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques.md
Labels: netlify-cms/pending_review

#7609 Mise à jour de data.insertion dans Produit
  content/_startups/data.insertion.md
Labels: netlify-cms/draft

#7685 Mise à jour de data.insertion dans Produit
  content/_startups/data.insertion.md
Labels: netlify-cms/draft

#7695 Mise à jour de 2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques dans Fiche de poste
  content/_jobs/2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques.md
Labels: netlify-cms/pending_review

#7694 Mise à jour de 2021-11-19-dev.full.stack dans Fiche de poste
  content/_jobs/2021-11-19-dev.full.stack.md
Labels: netlify-cms/pending_review

#7687 Mise à jour de 2021-07-22-un.e.developpeur.euse.fullstack dans Fiche de poste
  content/_jobs/2021-07-22-un.e.developpeur.euse.fullstack.md
Labels: netlify-cms/draft

#7724 Mise à jour de 2017-10-16-developpeur-mrs dans Fiche de poste
  content/_jobs/2017-10-16-developpeur-mrs.md
Labels: netlify-cms/pending_review

#7726 Création de 2021-11-24-un.e.charge.e.de.deploiement dans Fiche de poste !
  content/_jobs/2021-11-24-un.e.charge.e.de.deploiement.md
Labels: netlify-cms/pending_publish

#7727 Mise à jour de 2017-10-16-developpeur-mrs dans Fiche de poste
  content/_jobs/2017-10-16-developpeur-mrs.md
Labels: netlify-cms/pending_publish

#7728 Mise à jour de 2017-10-16-developpeur-mrs dans Fiche de poste
  content/_jobs/2017-10-16-developpeur-mrs.md
Labels: netlify-cms/draft

#7665 Mise à jour de nathalie.dupasquier dans Membre
  content/_authors/nathalie.dupasquier.md
Labels: netlify-cms/pending_publish

#7672 Mise à jour de renaud.pons dans Membre
  content/_authors/renaud.pons.md
Labels: netlify-cms/pending_publish

#7452 Mise à jour de au-compost-mitoyen dans Produit
  content/_startups/au-compost-mitoyen.md
Labels: netlify-cms/draft

#7733 Création de 2021-11-25-charge.e.de.deploiement.aupres.du.secteur.public.-.jeveuxaider-gouv-fr dans Fiche de poste !
  content/_jobs/2021-11-25-charge.e.de.deploiement.aupres.du.secteur.public.-.jeveuxaider-gouv-fr.md
Labels: netlify-cms/pending_publish

#7736 Création de 2021-11-25-designer.ux dans Fiche de poste !
  content/_jobs/2021-11-25-designer.ux.md
Labels: netlify-cms/pending_review

#7767 Mise à jour de marc.gavanier dans Membre
  content/_authors/marc.gavanier.md
Labels: netlify-cms/pending_review

#7761 Mise à jour de 2021-11-25-designer.ux dans Fiche de poste
  content/_jobs/2021-11-25-designer.ux.md
Labels: netlify-cms/pending_review

#7758 Mise à jour de sylvain.mahe dans Membre
  content/_authors/sylvain.mahe.md
Labels: netlify-cms/draft
