Repository betagouv/beta.gouv.fr, pull requests merged in 2021-10, with the labels that each got.

#7222 Création de talents.numeriques dans Produit !
  content/_startups/talents.numeriques.md
Labels: netlify-cms/pending_review

#7234 Mise à jour de clement.berthou dans Membre
  content/_authors/clement.berthou.md
Labels: netlify-cms/pending_publish

#7251 Mise à jour de disinfo dans Produit
  content/_startups/disinfo.md
Labels: netlify-cms/draft

#7304 Mise à jour de thibault.desjardins dans Membre
  content/_authors/thibault.desjardins.md
Labels: netlify-cms/pending_publish

#7323 Création de expresso dans Produit !
  content/_startups/expresso.md
Labels: netlify-cms/draft
