Repository betagouv/beta.gouv.fr, pull requests merged in 2021-12, with the labels that each got.

#7793 Mise à jour de 2021-11-25-designer.ux dans Fiche de poste
  content/_jobs/2021-11-25-designer.ux.md
Labels: netlify-cms/pending_review

#7792 Mise à jour de a-just dans Produit
  content/_startups/a-just.md
Labels: netlify-cms/pending_review

#7765 Mise à jour de davy.braun dans Membre
  content/_authors/davy.braun.md
Labels: netlify-cms/draft

#7791 Mise à jour de 2021-11-19-dev.full.stack dans Fiche de poste
  content/_jobs/2021-11-19-dev.full.stack.md
Labels: netlify-cms/pending_review

#7795 Mise à jour de 2021-11-24-un.e.charge.e.de.deploiement dans Fiche de poste
  content/_jobs/2021-11-24-un.e.charge.e.de.deploiement.md
Labels: netlify-cms/draft

#7796 Mise à jour de 2021-11-25-charge.e.de.deploiement.aupres.du.secteur.public.-.jeveuxaider-gouv-fr dans Fiche de poste
  content/_jobs/2021-11-25-charge.e.de.deploiement.aupres.du.secteur.public.-.jeveuxaider-gouv-fr.md
Labels: netlify-cms/draft

#7802 Mise à jour de 2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques dans Fiche de poste
  content/_jobs/2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques.md
Labels: netlify-cms/pending_review

#7815 Mise à jour de adrien.plantureux dans Membre
  content/_authors/adrien.plantureux.md
Labels: netlify-cms/pending_publish

#7818 Mise à jour de 2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques dans Fiche de poste
  content/_jobs/2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques.md
Labels: netlify-cms/draft

#7822 Mise à jour de 2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques dans Fiche de poste
  content/_jobs/2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques.md
Labels: netlify-cms/draft

#7596 MAJ Fiche produit sndv_maritime.md
  content/_startups/sndv_maritime.md
Labels: En discussion

#7849 Mise à jour de 2021-11-17-charge.e.de.croissance dans Fiche de poste
  content/_jobs/2021-11-17-charge.e.de.croissance.md
Labels: netlify-cms/draft

#7850 Création de 2021-12-06-developpeur.euse.web.senior dans Fiche de poste !
  content/_jobs/2021-12-06-developpeur.euse.web.senior.md
Labels: netlify-cms/pending_review

#7852 Mise à jour de 2021-12-06-developpeur.euse.web.senior dans Fiche de poste
  content/_jobs/2021-12-06-developpeur.euse.web.senior.md
Labels: netlify-cms/pending_publish

#7841 Création de ethique.en.sante.numerique dans Produit !
  content/_startups/ethique.en.sante.numerique.md
Labels: netlify-cms/draft

#7853 Mise à jour de 2021-12-06-developpeur.euse.web.senior dans Fiche de poste
  content/_jobs/2021-12-06-developpeur.euse.web.senior.md
Labels: netlify-cms/draft

#7854 Mise à jour de 2021-12-06-developpeur.euse.web.senior dans Fiche de poste
  content/_jobs/2021-12-06-developpeur.euse.web.senior.md
Labels: netlify-cms/draft

#7856 Mise à jour de 2021-12-06-developpeur.euse.web.senior dans Fiche de poste
  content/_jobs/2021-12-06-developpeur.euse.web.senior.md
Labels: netlify-cms/draft

#7858 Mise à jour de 2021-12-06-developpeur.euse.web.senior dans Fiche de poste
  content/_jobs/2021-12-06-developpeur.euse.web.senior.md
Labels: netlify-cms/pending_publish

#7864 Mise à jour de didoc dans Produit
  content/_startups/didoc.md
Labels: netlify-cms/draft

#7891 Mise à jour de monsuivipsy dans Produit
  content/_startups/monsuivipsy.md
Labels: netlify-cms/draft

#7898 Mise à jour de 2021-11-10-charge.e.d.assistance.aux.utilisateurs.et.d.animation.des.referents dans Fiche de poste
  content/_jobs/2021-11-10-charge.e.d.assistance.aux.utilisateurs.et.d.animation.des.referents.md
Labels: netlify-cms/draft

#7912 Création de 2021-12-09-chargee.ou.charge.de.deploiement dans Fiche de poste !
  content/_jobs/2021-12-09-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/pending_publish

#7913 Mise à jour de 2021-12-09-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2021-12-09-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/pending_publish

#7914 Mise à jour de 2021-12-09-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2021-12-09-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/pending_publish

#7836 Mise à jour de la-bonne-boite dans Produit
  content/_startups/la-bonne-boite.md
Labels: netlify-cms/draft

#7920 Mise à jour de 2021-12-09-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2021-12-09-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/draft

#7922 Mise à jour de 2021-12-09-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2021-12-09-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/draft

#7926 Mise à jour de ivan.gabriele dans Membre
  content/_authors/ivan.gabriele.md
Labels: netlify-cms/pending_publish

#7946 Mise à jour de johan.girod dans Membre
  content/_authors/johan.girod.md
Labels: netlify-cms/draft

#7940 Mise à jour de nadeige.couthon dans Membre
  content/_authors/nadeige.couthon.md
Labels: netlify-cms/draft

#7956 Mise à jour de quentin.kurtz dans Membre
  content/_authors/quentin.kurtz.md
Labels: netlify-cms/pending_review

#7973 Mise à jour de adrien.laville dans Membre
  content/_authors/adrien.laville.md
Labels: netlify-cms/draft

#7965 Mise à jour de bertille.magnonpujo dans Membre
  content/_authors/bertille.magnonpujo.md
Labels: netlify-cms/draft

#7962 Mise à jour de fanny.dauchez dans Membre
  content/_authors/fanny.dauchez.md
Labels: netlify-cms/pending_review

#7980 Mise à jour de alexis.leclerc dans Membre
  content/_authors/alexis.leclerc.md
Labels: netlify-cms/pending_publish

#7985 Mise à jour de julien.rayneau dans Membre
  content/_authors/julien.rayneau.md
Labels: netlify-cms/pending_review

#7621 Création de coursconsult dans Produit !
  content/_startups/coursconsult.md
Labels: En discussion

#6848 Investigations du PNI
  content/_startups/anct-pni-1.md
  content/_startups/anct-pni-10.md
  content/_startups/anct-pni-11.md
  content/_startups/anct-pni-12.md
  content/_startups/anct-pni-13.md
  content/_startups/anct-pni-14.md
  content/_startups/anct-pni-15.md
  content/_startups/anct-pni-16.md
  content/_startups/anct-pni-17.md
  content/_startups/anct-pni-18.md
  content/_startups/anct-pni-19.md
  content/_startups/anct-pni-2.md
  content/_startups/anct-pni-20.md
  content/_startups/anct-pni-21.md
  content/_startups/anct-pni-22.md
  content/_startups/anct-pni-23.md
  content/_startups/anct-pni-24.md
  content/_startups/anct-pni-25.md
  content/_startups/anct-pni-26.md
  content/_startups/anct-pni-27.md
  content/_startups/anct-pni-28.md
  content/_startups/anct-pni-29.md
  content/_startups/anct-pni-3.md
  content/_startups/anct-pni-30.md
  content/_startups/anct-pni-31.md
  content/_startups/anct-pni-32.md
  content/_startups/anct-pni-33.md
  content/_startups/anct-pni-34.md
  content/_startups/anct-pni-35.md
  content/_startups/anct-pni-36.md
  content/_startups/anct-pni-37.md
  content/_startups/anct-pni-38.md
  content/_startups/anct-pni-39.md
  content/_startups/anct-pni-4.md
  content/_startups/anct-pni-40.md
  content/_startups/anct-pni-41.md
  content/_startups/anct-pni-42.md
  content/_startups/anct-pni-43.md
  content/_startups/anct-pni-44.md
  content/_startups/anct-pni-45.md
  content/_startups/anct-pni-46.md
  content/_startups/anct-pni-47.md
  content/_startups/anct-pni-48.md
  content/_startups/anct-pni-49.md
  content/_startups/anct-pni-5.md
  content/_startups/anct-pni-50.md
  content/_startups/anct-pni-6.md
  content/_startups/anct-pni-7.md
  content/_startups/anct-pni-8.md
  content/_startups/anct-pni-9.md
  content/_startups/anti-gaspi-cantine.md
Labels: help wanted

#7987 Création de 2021-12-13-developpeur.developpeuse.full-stack dans Fiche de poste !
  content/_jobs/2021-12-13-developpeur.developpeuse.full-stack.md
Labels: netlify-cms/pending_review

#7988 Mise à jour de adrien.di_pasquale dans Membre
  content/_authors/adrien.di_pasquale.md
Labels: netlify-cms/pending_review

#7989 Mise à jour de amelle.el-bakkal dans Membre
  content/_authors/amelle.el-bakkal.md
Labels: netlify-cms/pending_review

#7990 Mise à jour de zero-logement-vacant dans Produit
  content/_startups/zero-logement-vacant.md
Labels: netlify-cms/draft

#7991 Création de 2021-12-14-developpeuse.-.developpeur.react.typescript dans Fiche de poste !
  content/_jobs/2021-12-14-developpeuse.-.developpeur.react.typescript.md
Labels: netlify-cms/pending_publish

#8006 Mise à jour de livio.lumbroso dans Membre
  content/_authors/livio.lumbroso.md
Labels: netlify-cms/pending_publish

#7896 Création de 2021-12-07-developpeuse.-.developpeur.fullstack.pour.immersion.facile dans Fiche de poste !
  content/_jobs/2021-12-07-developpeuse.-.developpeur.fullstack.pour.immersion.facile.md
Labels: netlify-cms/pending_review

#8023 Mise à jour de zero-logement-vacant dans Produit
  content/_startups/zero-logement-vacant.md
Labels: netlify-cms/draft

#8075 Mise à jour de nicolas.bouilleaud dans Membre
  content/_authors/nicolas.bouilleaud.md
Labels: netlify-cms/pending_review

#8082 Mise à jour de lina.cham dans Membre
  content/_authors/lina.cham.md
Labels: netlify-cms/draft

#8086 Mise à jour de thomas.honnet dans Membre
  content/_authors/thomas.honnet.md
Labels: netlify-cms/draft

#8076 Mise à jour de raphael.huchet dans Membre
  content/_authors/raphael.huchet.md
Labels: netlify-cms/draft

#8067 Mise à jour de tristan.roue dans Membre
  content/_authors/tristan.roue.md
Labels: netlify-cms/draft

#7964 Mise à jour de olivier.gerard dans Membre
  content/_authors/olivier.gerard.md
Labels: netlify-cms/pending_publish

#8107 Mise à jour de a-just dans Produit
  content/_startups/a-just.md
Labels: netlify-cms/pending_review

#8110 Mise à jour de 2021-11-25-designer.ux dans Fiche de poste
  content/_jobs/2021-11-25-designer.ux.md
Labels: netlify-cms/pending_review

#8109 Mise à jour de brice.durand dans Membre
  content/_authors/brice.durand.md
Labels: netlify-cms/pending_publish

#8014 Mise à jour de fabrique-dgfip dans Incubateur
  content/_incubators/fabrique-dgfip.md
Labels: netlify-cms/pending_review

#8119 Mise à jour de marion.gros dans Membre
  content/_authors/marion.gros.md
Labels: netlify-cms/pending_review

#8142 Mise à jour de marie.briche dans Membre
  content/_authors/marie.briche.md
Labels: netlify-cms/pending_publish

#8147 Mise à jour de sofia.boulaarab dans Membre
  content/_authors/sofia.boulaarab.md
Labels: netlify-cms/pending_review

#8085 Mise à jour de gael.demette dans Membre
  content/_authors/gael.demette.md
Labels: netlify-cms/pending_publish

#8155 Mise à jour de raphael.odini dans Membre
  content/_authors/raphael.odini.md
Labels: netlify-cms/pending_publish

#8098 Mise à jour de bertille.magnonpujo dans Membre
  content/_authors/bertille.magnonpujo.md
Labels: netlify-cms/draft

#8066 Mise à jour de damien.boyer dans Membre
  content/_authors/damien.boyer.md
Labels: netlify-cms/pending_publish

#8163 Mise à jour de florian.briand dans Membre
  content/_authors/florian.briand.md
Labels: netlify-cms/pending_publish

#8144 Mise à jour de aymeric.faivre dans Membre
  content/_authors/aymeric.faivre.md
Labels: netlify-cms/pending_review

#8157 Mise à jour de yannick.jacqueline dans Membre
  content/_authors/yannick.jacqueline.md
Labels: netlify-cms/draft

#8206 Mise à jour de marie.bernard dans Membre
  content/_authors/marie.bernard.md
Labels: netlify-cms/pending_publish

#8156 Mise à jour de alexandre.annic dans Membre
  content/_authors/alexandre.annic.md
Labels: netlify-cms/draft

#7984 Mise à jour de marie.gasnier dans Membre
  content/_authors/marie.gasnier.md
Labels: netlify-cms/pending_review

#8164 Mise à jour de nicolas.kokla dans Membre
  content/_authors/nicolas.kokla.md
Labels: netlify-cms/draft

#8129 Mise à jour de etienne.weil dans Membre
  content/_authors/etienne.weil.md
Labels: netlify-cms/pending_publish

#8220 Création de 2021-12-22-dev.full-stack.f.h.-.a-just dans Fiche de poste !
  content/_jobs/2021-12-22-dev.full-stack.f.h.-.a-just.md
Labels: netlify-cms/pending_review

#8234 Création de 2021-12-23-developpeuse.ou.developpeur.fullstack dans Fiche de poste !
  content/_jobs/2021-12-23-developpeuse.ou.developpeur.fullstack.md
Labels: netlify-cms/pending_publish

#8236 Création de 2021-12-23-une.ou.un.designer.ux.ui.pour.la.startup.delta-v dans Fiche de poste !
  content/_jobs/2021-12-23-une.ou.un.designer.ux.ui.pour.la.startup.delta-v.md
Labels: netlify-cms/pending_publish

#8238 Mise à jour de sam.bzez dans Membre
  content/_authors/sam.bzez.md
Labels: netlify-cms/pending_publish

#8282 Mise à jour de radia.difallah dans Membre
  content/_authors/radia.difallah.md
Labels: netlify-cms/pending_review

#8280 Mise à jour de amaury.dubot dans Membre
  content/_authors/amaury.dubot.md
Labels: netlify-cms/pending_publish

#8279 Mise à jour de alexandre.grimault dans Membre
  content/_authors/alexandre.grimault.md
Labels: netlify-cms/pending_review

#8227 Mise à jour de joeffrey.arruyer dans Membre
  content/_authors/joeffrey.arruyer.md
Labels: netlify-cms/draft
