Repository betagouv/beta.gouv.fr, pull requests merged in 2021-06, with the labels that each got.

#6090 Mise à jour de chauffage-urbain dans Produit
  content/_startups/chauffage-urbain.md
Labels: netlify-cms/draft

#6121 Mise à jour de mano dans Produit
  content/_startups/mano.md
Labels: netlify-cms/draft

#6130 Mise à jour de 2021-05-04-mobilic-recrute-un-e-business-developer dans Fiche de poste
  content/_jobs/2021-05-04-mobilic-recrute-un-e-business-developer.md
Labels: netlify-cms/draft

#6131 Mise à jour de henry.ciesielski dans Membre
  content/_authors/henry.ciesielski.md
Labels: netlify-cms/draft

#6132 Mise à jour de benjamin.doberset dans Membre
  content/_authors/benjamin.doberset.md
Labels: netlify-cms/draft

#6134 Update olivier.gerard.md
  content/_authors/olivier.gerard.md
Labels: merge it !

#6144 Mise à jour de fanny.cheung dans Membre
  content/_authors/fanny.cheung.md
Labels: netlify-cms/draft

#6140 Mise à jour de AidESS-Relance dans Produit
  content/_startups/AidESS-Relance.md
Labels: netlify-cms/draft

#6148 Update florian.enoh.md
  content/_authors/florian.enoh.md
Labels: merge it !

#6129 update end date for Nancya Godeau
  content/_authors/nancya.godeau.md
Labels: merge it !

#6137 Ajoute les statistiques de Recosanté
  content/_startups/recosante.md
Labels: merge it !

#6117 correction ortho
  _pages/programme/investigation.md
Labels: merge it !

#6126 Extend end date for alexandre.annic
  content/_authors/alexandre.annic.md
Labels: merge it !

#6111 Update paul.burgun.md
  content/_authors/paul.burgun.md
Labels: merge it !

#6092 Mise à jour de pauline.eyherabide dans Membre
  content/_authors/pauline.eyherabide.md
Labels: merge it !

#6072 Update alejandro.mantecon-guillen.md
  content/_authors/alejandro.mantecon-guillen.md
Labels: modifications nécessaires

#6162 Mise à jour de damien.boyer dans Membre
  content/_authors/damien.boyer.md
Labels: netlify-cms/pending_publish

#6161 Mise à jour de morgan.izquierdo dans Membre
  content/_authors/morgan.izquierdo.md
Labels: netlify-cms/draft

#6165 Mise à jour de alexia.gazel dans Membre
  content/_authors/alexia.gazel.md
Labels: netlify-cms/draft

#6185 Mise à jour de 2021-05-31-un-e.charge-e.de.produit dans Fiche de poste
  content/_jobs/2021-05-31-un-e.charge-e.de.produit.md
Labels: netlify-cms/draft

#6186 Création de 2021-06-10-un-e.designer.ui.ux dans Fiche de poste !
  content/_jobs/2021-06-10-un-e.designer.ui.ux.md
Labels: netlify-cms/draft

#6189 Création de 2021-06-10-bizdev.et.animation.partenariale dans Fiche de poste !
  content/_jobs/2021-06-10-bizdev.et.animation.partenariale.md
Labels: netlify-cms/draft

#6191 Mise à jour de 2021-06-10-bizdev.et.animation.partenariale dans Fiche de poste
  content/_jobs/2021-06-10-bizdev.et.animation.partenariale.md
Labels: netlify-cms/draft

#6190 Création de 2021-06-10-charge-e.de.laffectation.du.suivi.de.signalements.et.animation.de.territoire dans Fiche de poste !
  content/_jobs/2021-06-10-charge-e.de.laffectation.du.suivi.de.signalements.et.animation.de.territoire.md
Labels: netlify-cms/draft

#6192 Mise à jour de 2021-06-10-charge-e.de.laffectation.du.suivi.de.signalements.et.animation.de.territoire dans Fiche de poste
  content/_jobs/2021-06-10-charge-e.de.laffectation.du.suivi.de.signalements.et.animation.de.territoire.md
Labels: netlify-cms/draft

#6193 Mise à jour de 2021-06-10-un-e.designer.ui.ux dans Fiche de poste
  content/_jobs/2021-06-10-un-e.designer.ui.ux.md
Labels: netlify-cms/draft

#6194 Mise à jour de 2021-06-10-un-e.designer.ui.ux dans Fiche de poste
  content/_jobs/2021-06-10-un-e.designer.ui.ux.md
Labels: netlify-cms/draft

#6196 Mise à jour de 2021-06-10-bizdev.et.animation.partenariale dans Fiche de poste
  content/_jobs/2021-06-10-bizdev.et.animation.partenariale.md
Labels: netlify-cms/draft

#6199 Mise à jour de 2021-06-10-un-e.designer.ui.ux dans Fiche de poste
  content/_jobs/2021-06-10-un-e.designer.ui.ux.md
Labels: netlify-cms/draft

#6195 Mise à jour de 2021-06-10-charge-e.de.laffectation.du.suivi.de.signalements.et.animation.de.territoire dans Fiche de poste
  content/_jobs/2021-06-10-charge-e.de.laffectation.du.suivi.de.signalements.et.animation.de.territoire.md
Labels: netlify-cms/draft

#6200 Mise à jour de 2021-06-10-bizdev.et.animation.partenariale dans Fiche de poste
  content/_jobs/2021-06-10-bizdev.et.animation.partenariale.md
Labels: netlify-cms/draft

#6169 Mise à jour de histologe dans Produit
  content/_startups/histologe.md
Labels: netlify-cms/draft

#6211 Mise à jour de 2021-05-27-developpeur.se.full.stack.-.python.django dans Fiche de poste
  content/_jobs/2021-05-27-developpeur.se.full.stack.-.python.django.md
Labels: netlify-cms/draft

#6223 Mise à jour de lauren.michel dans Membre
  content/_authors/lauren.michel.md
Labels: netlify-cms/draft

#6256 Création de 2021-06-15-designer.ux.ui dans Fiche de poste !
  content/_jobs/2021-06-15-designer.ux.ui.md
Labels: netlify-cms/draft

#6269 Mise à jour de 2021-06-15-designer.ux.ui dans Fiche de poste
  content/_jobs/2021-06-15-designer.ux.ui.md
Labels: netlify-cms/draft

#6276 Mise à jour de anne.poirot dans Membre
  content/_authors/anne.poirot.md
Labels: netlify-cms/draft

#6277 Mise à jour de caroline-lucile.didier dans Membre
  content/_authors/caroline-lucile.didier.md
Labels: netlify-cms/draft

#6287 Création de 2021-06-17-charge-e.de.deploiement dans Fiche de poste !
  content/_jobs/2021-06-17-charge-e.de.deploiement.md
Labels: netlify-cms/pending_publish

#6116 Création de tchap dans Produit !
  content/_startups/tchap.md
Labels: netlify-cms/draft

#6280 Mise à jour de 2021-06-10-un-e.designer.ui.ux dans Fiche de poste
  content/_jobs/2021-06-10-un-e.designer.ui.ux.md
Labels: netlify-cms/draft

#6231 Mise à jour de 2021-06-10-bizdev.et.animation.partenariale dans Fiche de poste
  content/_jobs/2021-06-10-bizdev.et.animation.partenariale.md
Labels: netlify-cms/draft

#6307 Mise à jour de penelope.liot dans Membre
  content/_authors/penelope.liot.md
Labels: netlify-cms/draft

#6309 Mise à jour de homologation dans Produit
  content/_startups/homologation.md
Labels: netlify-cms/pending_publish

#6311 Mise à jour de 2021-06-15-designer.ux.ui dans Fiche de poste
  content/_jobs/2021-06-15-designer.ux.ui.md
Labels: netlify-cms/draft

#6333 Mise à jour de 2021-06-08-bizdev-territoires-en-transitions dans Fiche de poste
  content/_jobs/2021-06-08-bizdev-territoires-en-transitions.md
Labels: netlify-cms/draft

#6334 Mise à jour de 2021-06-08-developpeuse-territoires-en-transitions dans Fiche de poste
  content/_jobs/2021-06-08-developpeuse-territoires-en-transitions.md
Labels: netlify-cms/draft

#6351 Mise à jour de clemence.martin dans Membre
  content/_authors/clemence.martin.md
Labels: netlify-cms/draft

#6340 Mise à jour de claire.casubolo dans Membre
  content/_authors/claire.casubolo.md
Labels: netlify-cms/draft

#6352 Cms/clem mrtn/beta.gouv.fr/authors/clemence.martin
  content/_authors/clemence.martin.md
Labels: merge it !

#6317 Mise à jour de nicolas.vallee dans Membre
  content/_authors/nicolas.vallee.md
Labels: netlify-cms/draft

#6320 Mise à jour de martin.ruau dans Membre
  content/_authors/martin.ruau.md
Labels: netlify-cms/draft

#6367 Mise à jour de melodie.dahi dans Membre
  content/_authors/melodie.dahi.md
Labels: netlify-cms/draft

#6370 Mise à jour de inca dans Produit
  content/_startups/inca.md
Labels: netlify-cms/draft

#6383 Création de 2021-06-29-un.e.developpeur.se.full.stack dans Fiche de poste !
  content/_jobs/2021-06-29-un.e.developpeur.se.full.stack.md
Labels: netlify-cms/draft

#6384 Création de 2021-06-29-un.e.charge.e.de.deploiement dans Fiche de poste !
  content/_jobs/2021-06-29-un.e.charge.e.de.deploiement.md
Labels: netlify-cms/draft

#6391 Mise à jour de ronan.james dans Membre
  content/_authors/ronan.james.md
Labels: netlify-cms/pending_publish

#6374 Mise à jour de maxime.dreau dans Membre
  content/_authors/maxime.dreau.md
Labels: netlify-cms/pending_publish

#6403 Mise à jour de salome.deschenes dans Membre
  content/_authors/salome.deschenes.md
Labels: netlify-cms/pending_publish

#6411 Mise à jour de raphael.odini dans Membre
  content/_authors/raphael.odini.md
Labels: netlify-cms/draft

#6401 Updating ITOU Team dates
  content/_authors/david.watrelot.md
  content/_authors/fanny.dauchez.md
  content/_authors/frederic.vergez.md
  content/_authors/marc.hertzog.md
  content/_authors/pieterjan.montens.md
  content/_authors/rodolphe.gagetta.md
  content/_authors/sebastien.reuiller.md
  content/_authors/sophie.garcia.md
Labels: merge it !
