Repository betagouv/beta.gouv.fr, pull requests merged in 2021-01, with the labels that each got.

#4840 Mise à jour de damien.boyer dans Membre
  content/_authors/damien.boyer.md
Labels: netlify-cms/pending_publish

#4841 Mise à jour de redouane.bouchane dans Membre
  content/_authors/redouane.bouchane.md
Labels: netlify-cms/draft

#4781 Update archifiltre.md
  content/_startups/archifiltre.md
Labels: modifications nécessaires

#4878 Update Alexandre De Pablo ending date
  content/_authors/alexandre.depablo.md
Labels: merge it !

#4898 Update nathalie.reyre.md
  content/_authors/nathalie.reyre.md
Labels: merge it !

#4913 Update sebastien.legoff.md
  content/_authors/sebastien.legoff.md
Labels: merge it !

#4912 Update yoann.kassi-vivier.md
  content/_authors/yoann.kassi-vivier.md
Labels: merge it !

#4911 Update maxime.perdu.md
  content/_authors/maxime.perdu.md
Labels: merge it !

#4910 Update camille.balenieri.md
  content/_authors/camille.balenieri.md
Labels: merge it !

#4896 Mise à jour de claire.vigier dans Membre
  content/_authors/claire.vigier.md
Labels: merge it !, netlify-cms/pending_publish

#4866 Mise à jour de etienne.weil dans Membre
  content/_authors/etienne.weil.md
Labels: merge it !, netlify-cms/draft

#4868 Correction du graphe de communauté
  assets/additional/js/community-chart.js
Labels: merge it !

#4850 Mise à jour de fanny.dauchez dans Membre
  content/_authors/fanny.dauchez.md
Labels: merge it !

#4494 Mise à jour de mes dates
  content/_authors/david.bruant.md
Labels: merge it !

#4999 Mise à jour de valentine.michaud dans Membre
  content/_authors/valentine.michaud.md
Labels: netlify-cms/pending_publish

#5013 Mise à jour de bettina.leblanc dans Membre
  content/_authors/bettina.leblanc.md
Labels: netlify-cms/draft

#5015 Mise à jour de lucas.charrier dans Membre
  content/_authors/lucas.charrier.md
Labels: netlify-cms/draft

#5016 Mise à jour de lucas.charrier dans Membre
  content/_authors/lucas.charrier.md
Labels: netlify-cms/draft

#4969 Mise à jour de clement.renault dans Membre
  content/_authors/clement.renault.md
Labels: netlify-cms/draft

#5042 Test automerge github action
  .github/workflows/automerge.yml
Labels: merge it !

#5044 Task/lucas/test automerge bot test
  .github/workflows/automerge.yml
  content/_authors/lucas.charrier.md
Labels: merge it !

#4507 Ajout d'un bot d'automerge
  .github/workflows/automerge.yml
Labels: merge it !

#5053 Task/add automerge
  .github/workflows/automerge.yml
Labels: merge it !

#5031 Mise à jour de estime dans Produit
  content/_startups/estime.md
Labels: netlify-cms/pending_publish

#5070 Mise à jour de lucas.charrier dans Membre
  content/_authors/lucas.charrier.md
Labels: netlify-cms/pending_publish

#5020 Update 2020-12-24-engagement-civique-RC-charge-deploiement.md
  content/_jobs/2020-12-24-engagement-civique-RC-charge-deploiement.md
Labels: merge it !

#5068 Update etavecceci
  content/_startups/etavecceci
Labels: merge it !

#5075 Task/add automerge
  .github/workflows/automerge.yml
  .github/workflows/tests.yml
Labels: merge it !

#5039 Mise à jour de lucas.detre dans Membre
  content/_authors/lucas.detre.md
Labels: merge it !, netlify-cms/draft

#5035 Mise à jour de jeremie.lanceleur dans Membre
  content/_authors/jeremie.lanceleur.md
Labels: merge it !, netlify-cms/draft

#5030 Create gap.md
  content/_startups/gap.md
Labels: merge it !

#5024 Update thibaud.chambert-loir.md
  content/_authors/thibaud.chambert-loir.md
Labels: merge it !

#4992 Update pole-emploi.md
  content/_incubators/pole-emploi.md
Labels: merge it !

#5093 Task/add automerge with token
  .github/workflows/automerge.yml
Labels: merge it !

#5096 Mise à jour de lucas.charrier dans Membre
  content/_authors/lucas.charrier.md
Labels: merge it !, netlify-cms/draft

#5097 Ne pas activer l'automerge si le secret n'est pas là
  .github/workflows/automerge.yml
Labels: merge it !

#5088 Mise à jour fiche produit mobilic
  content/_startups/mobilic.md
Labels: merge it !

#5034 Création de stephen.bastard dans Membre !
  content/_authors/stephen.bastard.md
Labels: merge it !, netlify-cms/pending_publish

#5038 Création de sandrine.chaize dans Membre !
  content/_authors/sandrine.chaize.md
Labels: merge it !, netlify-cms/pending_publish

#5102 Mise à jour de lucas.charrier dans Membre
  content/_authors/lucas.charrier.md
Labels: merge it !, netlify-cms/pending_publish

#5069 Test to remove publish button
  admin/index.html
Labels: merge it !, on_hold

#5111 Tasks/text better ux for netlifycms
  admin/index.html
Labels: merge it !

#5122 Création de catalogue.des.formations.en.apprentissage dans Produit !
  content/_startups/catalogue.des.formations.en.apprentissage.md
Labels: netlify-cms/draft

#5128 Mise à jour de pierre-olivier.mauguet dans Membre
  content/_authors/pierre-olivier.mauguet.md
Labels: netlify-cms/draft

#5129 Changement de l'ordre des sections dans netlify cms
  admin/config.yml
Labels: merge it !

#5140 Format plus guidé pour le champs description dans netlify cms lors de la création d'un produit
  admin/config.yml
Labels: merge it !

#5148 Added header favicon
  admin/config.yml
  admin/index.html
Labels: merge it !

#5153 Changed button color
  admin/index.html
Labels: merge it !
