Repository betagouv/beta.gouv.fr, pull requests merged in 2021-09, with the labels that each got.

#6966 Mise à jour de delta.v dans Produit
  content/_startups/delta.v.md
Labels: netlify-cms/draft

#6955 Mise à jour de benjamin.vanderlynden dans Membre
  content/_authors/benjamin.vanderlynden.md
Labels: netlify-cms/draft

#6986 Mise à jour de nicolas.enjalbert dans Membre
  content/_authors/nicolas.enjalbert.md
Labels: netlify-cms/pending_review

#6935 Mise à jour de renaud.pons dans Membre
  content/_authors/renaud.pons.md
Labels: netlify-cms/pending_review

#6985 Mise à jour de envergo dans Produit
  content/_startups/envergo.md
Labels: netlify-cms/pending_review

#6923 Mise à jour de article.40 dans Produit
  content/_startups/article.40.md
Labels: netlify-cms/pending_publish

#7038 Mise à jour de lucien.mollard dans Membre
  content/_authors/lucien.mollard.md
Labels: netlify-cms/draft

#7034 Mise à jour de thierry.verrecchia dans Membre
  content/_authors/thierry.verrecchia.md
Labels: netlify-cms/draft

#7050 Mise à jour de 2021-07-27-un.ou.une.designer.ux.ui dans Fiche de poste
  content/_jobs/2021-07-27-un.ou.une.designer.ux.ui.md
Labels: netlify-cms/draft

#7056 Création de bureaux.vacants dans Produit !
  content/_startups/bureaux.vacants.md
Labels: netlify-cms/pending_review

#7057 Mise à jour de bureaux.vacants dans Produit
  content/_startups/bureaux.vacants.md
Labels: netlify-cms/pending_review

#7047 Mise à jour de caroline.lawson dans Membre
  content/_authors/caroline.lawson.md
Labels: netlify-cms/pending_review

#7048 Mise à jour de michael.boitin dans Membre
  content/_authors/michael.boitin.md
Labels: netlify-cms/pending_review

#7058 Mise à jour de bureaux.vacants dans Produit
  content/_startups/bureaux.vacants.md
Labels: netlify-cms/pending_review

#7072 Mise à jour de philippe.libat dans Membre
  content/_authors/philippe.libat.md
Labels: netlify-cms/draft

#7063 Création de 2021-09-13-responsable.communication.de.jeveuxaider-gouv-fr dans Fiche de poste !
  content/_jobs/2021-09-13-responsable.communication.de.jeveuxaider-gouv-fr.md
Labels: netlify-cms/pending_publish

#7110 Mise à jour de aymeric.raoult dans Membre
  content/_authors/aymeric.raoult.md
Labels: netlify-cms/pending_review

#7118 Mise à jour de 2021-09-07-charge-e.de.communication dans Fiche de poste
  content/_jobs/2021-09-07-charge-e.de.communication.md
Labels: netlify-cms/draft

#7119 Mise à jour de 2021-09-07-ui.designer dans Fiche de poste
  content/_jobs/2021-09-07-ui.designer.md
Labels: netlify-cms/draft

#7084 Update marion.guillet.md
  content/_authors/marion.guillet.md
Labels: modifications nécessaires

#7131 Mise à jour de louisjean.teitelbaum dans Membre
  content/_authors/louisjean.teitelbaum.md
Labels: netlify-cms/pending_publish

#7144 Mise à jour de a-just dans Produit
  content/_startups/a-just.md
Labels: netlify-cms/pending_review

#7146 Création de 2021-09-22-dev.full-stack.senior dans Fiche de poste !
  content/_jobs/2021-09-22-dev.full-stack.senior.md
Labels: netlify-cms/pending_review

#7145 Mise à jour de 2021-09-13-responsable.communication.de.jeveuxaider-gouv-fr dans Fiche de poste
  content/_jobs/2021-09-13-responsable.communication.de.jeveuxaider-gouv-fr.md
Labels: netlify-cms/pending_publish

#7167 Mise à jour de 2021-05-12-des.developpeuses.et.developpeurs.seniors.pour.les.startups.detat.du.ministere.de.la.transition.ecologique dans Fiche de poste
  content/_jobs/2021-05-12-des.developpeuses.et.developpeurs.seniors.pour.les.startups.detat.du.ministere.de.la.transition.ecologique.md
Labels: netlify-cms/draft

#7168 Création de oufaalim dans Produit !
  content/_startups/oufaalim.md
Labels: netlify-cms/draft

#7179 Création de competence.validee dans Produit !
  content/_startups/competence.validee.md
Labels: netlify-cms/pending_review

#7191 Mise à jour de sebastien.poirot dans Membre
  content/_authors/sebastien.poirot.md
Labels: netlify-cms/pending_review
