Repository betagouv/beta.gouv.fr, pull requests merged in 2022-01, with the labels that each got.

#8295 Mise à jour de mathilde.menil dans Membre
  content/_authors/mathilde.menil.md
Labels: netlify-cms/pending_publish

#8300 Mise à jour de francois.romain dans Membre
  content/_authors/francois.romain.md
Labels: netlify-cms/draft

#8298 Mise à jour de maxime.dreau dans Membre
  content/_authors/maxime.dreau.md
Labels: netlify-cms/pending_publish

#8310 Mise à jour de 2021-12-06-developpeur.euse.web.senior dans Fiche de poste
  content/_jobs/2021-12-06-developpeur.euse.web.senior.md
Labels: netlify-cms/draft

#8311 Mise à jour de 2021-12-09-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2021-12-09-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/draft

#8312 Mise à jour de sophie.garcia dans Membre
  content/_authors/sophie.garcia.md
Labels: netlify-cms/draft

#8347 Mise à jour de 2021-10-24-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2021-10-24-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/pending_review

#8294 Mise à jour de nathalie.dupasquier dans Membre
  content/_authors/nathalie.dupasquier.md
Labels: netlify-cms/draft

#8137 Mise à jour de nicolas.toublanc dans Membre
  content/_authors/nicolas.toublanc.md
Labels: netlify-cms/draft

#8355 Mise à jour de sylvain.toe dans Membre
  content/_authors/sylvain.toe.md
Labels: netlify-cms/draft

#8385 Mise à jour de dora dans Produit
  content/_startups/dora.md
Labels: netlify-cms/draft

#8386 Mise à jour de dora dans Produit
  content/_startups/dora.md
Labels: netlify-cms/draft

#8391 Mise à jour de dora dans Produit
  content/_startups/dora.md
Labels: netlify-cms/draft

#8405 Création de 2022-01-10-charge.ou.chargee.d.acquisition.pour.le.marche.de.linclusion dans Fiche de poste !
  content/_jobs/2022-01-10-charge.ou.chargee.d.acquisition.pour.le.marche.de.linclusion.md
Labels: netlify-cms/pending_review

#8411 Création de 2022-01-10-developpeuse.-.developpeur dans Fiche de poste !
  content/_jobs/2022-01-10-developpeuse.-.developpeur.md
Labels: netlify-cms/pending_review

#8412 Création de 2022-01-10-designeuse.-.designer dans Fiche de poste !
  content/_jobs/2022-01-10-designeuse.-.designer.md
Labels: netlify-cms/pending_publish

#8414 Mise à jour de delphine.clerc dans Membre
  content/_authors/delphine.clerc.md
Labels: netlify-cms/draft

#8415 Mise à jour de gaspard.granger dans Membre
  content/_authors/gaspard.granger.md
Labels: netlify-cms/draft

#8417 Création de 2022-01-10-developpeuse.-.developpeur.1 dans Fiche de poste !
  content/_jobs/2022-01-10-developpeuse.-.developpeur.1.md
Labels: netlify-cms/draft

#8420 Mise à jour de 2022-01-10-developpeuse.-.developpeur.1 dans Fiche de poste
  content/_jobs/2022-01-10-developpeuse.-.developpeur.1.md
Labels: netlify-cms/draft

#8427 Création de 2022-01-10-designeuse.-.designer.1 dans Fiche de poste !
  content/_jobs/2022-01-10-designeuse.-.designer.1.md
Labels: netlify-cms/draft

#8422 Mise à jour de 2022-01-10-developpeuse.-.developpeur.1 dans Fiche de poste
  content/_jobs/2022-01-10-developpeuse.-.developpeur.1.md
Labels: netlify-cms/draft

#8428 Mise à jour de 2022-01-10-developpeuse.-.developpeur.1 dans Fiche de poste
  content/_jobs/2022-01-10-developpeuse.-.developpeur.1.md
Labels: netlify-cms/draft

#8429 Mise à jour de 2022-01-10-designeuse.-.designer.1 dans Fiche de poste
  content/_jobs/2022-01-10-designeuse.-.designer.1.md
Labels: netlify-cms/draft

#8193 Mise à jour de 2021-11-19-dev.full.stack dans Fiche de poste
  content/_jobs/2021-11-19-dev.full.stack.md
Labels: netlify-cms/pending_publish

#8194 Mise à jour de 2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques dans Fiche de poste
  content/_jobs/2021-11-19-personne.en.charge.du.deploiement.-.responsable.de.louverture.des.donnees.de.subventions.publiques.md
Labels: netlify-cms/pending_publish

#8425 Mise à jour de envergo dans Produit
  content/_startups/envergo.md
Labels: netlify-cms/draft

#8441 Mise à jour de thibaud.chambert-loir dans Membre
  content/_authors/thibaud.chambert-loir.md
Labels: netlify-cms/pending_publish

#8455 Mise à jour de yannick.prost dans Membre
  content/_authors/yannick.prost.md
Labels: netlify-cms/pending_review

#8460 Mise à jour de 2022-01-10-designeuse.-.designer.1 dans Fiche de poste
  content/_jobs/2022-01-10-designeuse.-.designer.1.md
Labels: netlify-cms/draft

#8461 Mise à jour de 2022-01-10-developpeuse.-.developpeur.1 dans Fiche de poste
  content/_jobs/2022-01-10-developpeuse.-.developpeur.1.md
Labels: netlify-cms/draft

#8474 Mise à jour de 2021-12-22-dev.full-stack.f.h.-.a-just dans Fiche de poste
  content/_jobs/2021-12-22-dev.full-stack.f.h.-.a-just.md
Labels: netlify-cms/pending_review

#8475 Mise à jour de a-just dans Produit
  content/_startups/a-just.md
Labels: netlify-cms/pending_review

#8477 Mise à jour de a-just dans Produit
  content/_startups/a-just.md
Labels: netlify-cms/pending_review

#8476 Mise à jour de 2021-12-22-dev.full-stack.f.h.-.a-just dans Fiche de poste
  content/_jobs/2021-12-22-dev.full-stack.f.h.-.a-just.md
Labels: netlify-cms/draft

#8397 Mise à jour de jeremy.ciepielewski dans Membre
  content/_authors/jeremy.ciepielewski.md
Labels: netlify-cms/draft

#8504 Mise à jour de histologe dans Produit
  content/_startups/histologe.md
Labels: netlify-cms/pending_publish

#8559 Mise à jour de data-subvention dans Produit
  content/_startups/data-subvention.md
Labels: netlify-cms/pending_review

#8589 Création de 2022-01-20-developpeuse.-.developpeur.fullstack.a.dominante.django dans Fiche de poste !
  content/_jobs/2022-01-20-developpeuse.-.developpeur.fullstack.a.dominante.django.md
Labels: netlify-cms/draft

#8592 Création de 2022-01-20-developpeuse.-.developpeur.full.stack.symfony dans Fiche de poste !
  content/_jobs/2022-01-20-developpeuse-developpeur-full-stack-symfony.md
Labels: netlify-cms/draft

#8593 Mise à jour de 2022-01-20-developpeuse.-.developpeur.fullstack.a.dominante.django dans Fiche de poste
  content/_jobs/2022-01-20-developpeuse.-.developpeur.fullstack.a.dominante.django.md
Labels: netlify-cms/draft

#8645 Création de 2022-01-25-profil.recherche.chargee.ou.charge.d.assistance.aux.utilisateurs.et.d.animation.des.referents.service.national.universel dans Fiche de poste !
  content/_jobs/2022-01-25-profil.recherche.chargee.ou.charge.d.assistance.aux.utilisateurs.et.d.animation.des.referents.service.national.universel.md
Labels: netlify-cms/pending_review

#8648 Mise à jour de psij dans Produit
  content/_startups/psij.md
Labels: netlify-cms/pending_review

#8726 Création de 2022-01-26-chargee.ou.charge.de.deploiement dans Fiche de poste !
  content/_jobs/2022-01-26-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/draft

#8727 Mise à jour de 2022-01-26-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2022-01-26-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/draft

#8728 Mise à jour de 2022-01-26-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2022-01-26-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/draft

#8735 Mise à jour de 2021-12-09-coach-mesure-impact-beta dans Fiche de poste
  content/_jobs/2021-12-09-coach-mesure-impact-beta.md
Labels: netlify-cms/pending_publish

#8737 Mise à jour de 2022-01-26-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2022-01-26-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/draft

#8748 Mise à jour de 2022-01-26-chargee.ou.charge.de.deploiement dans Fiche de poste
  content/_jobs/2022-01-26-chargee.ou.charge.de.deploiement.md
Labels: netlify-cms/draft

#8713 Création de 2022-01-26-un-e.gestionnaire.de.produit.product.owner dans Fiche de poste !
  content/_jobs/2022-01-26-un-e.gestionnaire.de.produit.product.owner.md
Labels: netlify-cms/pending_review

#8782 Mise à jour de data-subvention dans Produit
  content/_startups/data-subvention.md
Labels: netlify-cms/pending_review
