Repository betagouv/beta.gouv.fr, pull requests merged in 2022-12, with the labels that each got.

#12240 Mise à jour de caroline.lawson dans Membre
  content/_authors/caroline.lawson.md
Labels: netlify-cms/pending_review

#12271 Mise à jour de maxime.lecoq dans Membre
  content/_authors/maxime.lecoq.md
Labels: netlify-cms/pending_review

#12066 Update christian.quest.md
  content/_authors/christian.quest.md
Labels: En discussion

#12072 Mise à jour de delta.v dans Produit
  content/_startups/delta.v.md
Labels: netlify-cms/draft

#12167 Mise à jour de michael.boitin dans Membre
  content/_authors/michael.boitin.md
Labels: netlify-cms/pending_review

#12175 Mise à jour de marjorie.colin dans Membre
  content/_authors/marjorie.colin.md
Labels: netlify-cms/pending_publish

#12343 Create atelier_meae.md
  content/_teams/atelier_meae.md
Labels: En attente review

#12382 Création de ddd dans Organisation !
  content/_organisations/ddd.md
Labels: netlify-cms/pending_review

#12384 Création de parcours.de.saisine dans Produit !
  content/_startups/parcours.de.saisine.md
  img/netlifycms/2209.-.ddd.-.analyse.formulaire.saisine1.jpg
  img/netlifycms/capture.d.e.cran.2022-10-06.a.11.08.03-.png
  img/netlifycms/capture.d.e.cran.2022-10-06.a.12.09.19-.png
Labels: netlify-cms/draft

#12393 Mise à jour de sndv_maritime dans Produit
  content/_startups/sndv_maritime.md
Labels: netlify-cms/draft

#12406 Mise à jour de a-just dans Produit
  content/_startups/a-just.md
Labels: netlify-cms/pending_review

#12410 Passage de REflex en alumni, rédaction du post-mortem
  content/_startups/reflex.md
Labels: netlify-cms/draft

#12530 Mise à jour de sebastien.legoff dans Membre
  content/_authors/sebastien.legoff.md
Labels: netlify-cms/pending_review

#12535 Mise à jour de mael.inizan dans Membre
  content/_authors/mael.inizan.md
Labels: netlify-cms/draft

#12539 Mise à jour de benoit.champy dans Membre
  content/_authors/benoit.champy.md
Labels: netlify-cms/draft

#12540 Mise à jour de clemence.martin dans Membre
  content/_authors/clemence.martin.md
Labels: netlify-cms/draft

#12542 Mise à jour de julien.parc dans Membre
  content/_authors/julien.parc.md
Labels: netlify-cms/draft

#12581 Mise à jour de dominique.pena dans Membre
  content/_authors/dominique.pena.md
Labels: netlify-cms/pending_review

#11932 Ajoute une description pour le gip
  content/_organisations/gip-inclusion.md
Labels: En attente review

#11549 Ajout fiche AudioConf
  content/_startups/audioconf.md
Labels: En attente review

#12610 Création de valorisation.des.stages.pro dans Produit !
  content/_authors/melodie.dahi.md
  content/_authors/stephane.maniaci.md
  content/_startups/valorisation.des.stages.pro.md
Labels: netlify-cms/draft

#12633 Mise à jour de setaccords dans Produit
  content/_startups/setaccords.md
Labels: netlify-cms/pending_review
