Repository betagouv/beta.gouv.fr, pull requests merged in 2022-05, with the labels that each got.

#9840 Mise à jour de 2021-12-07-developpeuse.-.developpeur.fullstack.pour.immersion.facile dans Fiche de poste
  content/_jobs/2021-12-07-developpeuse.-.developpeur.fullstack.pour.immersion.facile.md
Labels: netlify-cms/pending_review

#9685 Mise à jour de Mon-suivi-social dans Produit
  content/_startups/Mon-suivi-social.md
Labels: netlify-cms/draft

#9850 Mise à jour de fedel dans Produit
  content/_startups/fedel.md
Labels: netlify-cms/pending_review

#9849 Mise à jour de polex dans Produit
  content/_startups/polex.md
Labels: netlify-cms/pending_review

#9862 Mise à jour de 2022-03-02-developpeur-se.frontend dans Fiche de poste
  content/_jobs/2022-03-02-developpeur-se.frontend.md
Labels: netlify-cms/draft

#9875 Mise à jour de sparte dans Produit
  content/_startups/sparte.md
Labels: netlify-cms/pending_review

#9732 Mise à jour de vanessa.ducloux dans Membre
  content/_authors/vanessa.ducloux.md
Labels: netlify-cms/pending_review

#9877 Mise à jour de camino dans Produit
  content/_startups/camino.md
Labels: netlify-cms/pending_review

#9416 Mise à jour de 2022-03-16-charge-e.de.deploiement.national.pour.lacceleration.de.la.startup.mon.suivi.justice dans Fiche de poste
  content/_jobs/2022-03-16-charge-e.de.deploiement.national.pour.lacceleration.de.la.startup.mon.suivi.justice.md
Labels: netlify-cms/pending_publish

#9894 Mise à jour de aides-territoires dans Produit
  content/_startups/aides-territoires.md
Labels: netlify-cms/pending_review

#9895 Mise à jour de dedale dans Produit
  content/_startups/dedale.md
Labels: netlify-cms/pending_review

#9899 Création de 2022-05-06-charge-e.de.deploiement dans Fiche de poste !
  content/_jobs/2022-05-06-charge-e.de.deploiement.md
Labels: netlify-cms/pending_review

#9908 Mise à jour de adrien.signorino dans Membre
  content/_authors/adrien.signorino.md
Labels: netlify-cms/draft

#9909 Mise à jour de fabien.tafforeau dans Membre
  content/_authors/fabien.tafforeau.md
Labels: netlify-cms/draft

#9919 Mise à jour de 2022-04-15-charge.e.de.deploiement.aupres.des.associations.pour.jeveuxaider-gouv-fr dans Fiche de poste
  content/_jobs/2022-04-15-charge.e.de.deploiement.aupres.des.associations.pour.jeveuxaider-gouv-fr.md
Labels: netlify-cms/draft

#9923 Mise à jour de locatio dans Produit
  content/_startups/locatio.md
Labels: netlify-cms/pending_review

#9924 Création de 2022-05-11-designeuse.ou.designeur.ui dans Fiche de poste !
  content/_jobs/2022-05-11-designeuse.ou.designeur.ui.md
Labels: netlify-cms/draft

#9925 Mise à jour de 2022-05-11-designeuse.ou.designeur.ui dans Fiche de poste
  content/_jobs/2022-05-11-designeuse.ou.designeur.ui.md
Labels: netlify-cms/draft

#9927 Mise à jour de linna.taing dans Membre
  content/_authors/linna.taing.md
Labels: netlify-cms/draft

#9933 Mise à jour de mathieu.mahr dans Membre
  content/_authors/mathieu.mahr.md
Labels: netlify-cms/draft

#9942 Création de 2022-05-12-charge-e.de.portefeuille.data.a.lincubateur.des.territoires dans Fiche de poste !
  content/_jobs/2022-05-12-charge-e.de.portefeuille.data.a.lincubateur.des.territoires.md
Labels: netlify-cms/draft

#9945 Création de plateforme.impact dans Produit !
  content/_startups/plateforme.impact.md
Labels: netlify-cms/pending_review

#9947 Création de 2022-05-12-charge.de.projet.territoires.connectes.et.durables.data.et.services.f.h dans Fiche de poste !
  content/_jobs/2022-05-12-charge.de.projet.territoires.connectes.et.durables.data.et.services.f.h.md
Labels: netlify-cms/draft

#9948 Mise à jour de 2022-04-06-un.e.charge.e.de.deploiement.pour.la.brigade.dintervention.numerique dans Fiche de poste
  content/_jobs/2022-04-06-un.e.charge.e.de.deploiement.pour.la.brigade.dintervention.numerique.md
Labels: netlify-cms/pending_review

#9953 Mise à jour de 2022-04-06-un.e.charge.e.de.deploiement.pour.la.brigade.dintervention.numerique dans Fiche de poste
  content/_jobs/2022-04-06-un.e.charge.e.de.deploiement.pour.la.brigade.dintervention.numerique.md
Labels: netlify-cms/pending_review

#9994 Mise à jour de 2022-03-11-developpeur.ou.une.developpeuse.front dans Fiche de poste
  content/_jobs/2022-03-11-developpeur.ou.une.developpeuse.front.md
Labels: netlify-cms/pending_review

#10007 Mise à jour de 2022-03-10-dev.front.angular.f.h.-.a-just dans Fiche de poste
  content/_jobs/2022-03-10-dev.front.angular.f.h.-.a-just.md
Labels: netlify-cms/draft

#9921 Mise à jour de dedale dans Produit
  content/_startups/dedale.md
Labels: netlify-cms/pending_review

#10027 Création de 2022-05-19-datagir.recrute.une.ou.un.responsable.seo dans Fiche de poste !
  content/_jobs/2022-05-19-datagir.recrute.une.ou.un.responsable.seo.md
Labels: netlify-cms/pending_review

#10030 Création de 2022-05-19-datagir.recrute.une.developpeuse.ou.un.developpeur.pour.ameliorer.le.calculateur.d.empreinte.climat.nosgestesclimat-fr dans Fiche de poste !
  content/_jobs/2022-05-19-datagir.recrute.une.developpeuse.ou.un.developpeur.pour.ameliorer.le.calculateur.d.empreinte.climat.nosgestesclimat-fr.md
Labels: netlify-cms/pending_review

#10059 Mise à jour de 1000.jours dans Produit
  content/_startups/1000.jours.md
Labels: netlify-cms/pending_publish

#10050 add skip links for quick access
  _includes/skip_links.html
  _layouts/dashboard.html
  _layouts/default.html
  _layouts/startups.html
Labels: a11y

#10069 Mise à jour de 2021-11-25-coach.customer.success.senior.pour.start-up.en.hyper.croissance dans Fiche de poste
  content/_jobs/2021-11-25-coach.customer.success.senior.pour.start-up.en.hyper.croissance.md
Labels: netlify-cms/draft

#10071 Mise à jour de 2021-11-22-charge-e.du.customer.success dans Fiche de poste
  content/_jobs/2021-11-22-charge-e.du.customer.success.md
Labels: netlify-cms/draft

#10074 Mise à jour de 2022-01-10-itou-data-analyst dans Fiche de poste
  content/_jobs/2022-01-10-itou-data-analyst.md
Labels: netlify-cms/draft

#10077 Mise à jour de zero-logement-vacant dans Produit
  content/_startups/zero-logement-vacant.md
Labels: netlify-cms/draft

#10079 Mise à jour de zero-logement-vacant dans Produit
  content/_startups/zero-logement-vacant.md
Labels: netlify-cms/draft

#10130 Mise à jour de 2022-05-19-datagir.recrute.une.ou.un.responsable.seo dans Fiche de poste
  content/_jobs/2022-05-19-datagir.recrute.une.ou.un.responsable.seo.md
Labels: netlify-cms/draft

#10131 Mise à jour de 2022-05-19-datagir.recrute.une.developpeuse.ou.un.developpeur.pour.ameliorer.le.calculateur.d.empreinte.climat.nosgestesclimat-fr dans Fiche de poste
  content/_jobs/2022-05-19-datagir.recrute.une.developpeuse.ou.un.developpeur.pour.ameliorer.le.calculateur.d.empreinte.climat.nosgestesclimat-fr.md
Labels: netlify-cms/draft

#10135 Mise à jour de 2022-05-30-ingenieur.e-donnees-trackdechets dans Fiche de poste
  content/_jobs/2022-05-30-ingenieur.e-donnees-trackdechets.md
Labels: netlify-cms/draft

#10136 Mise à jour de 2022-05-30-ingenieur.e-donnees-trackdechets dans Fiche de poste
  content/_jobs/2022-05-30-ingenieur.e-donnees-trackdechets.md
Labels: netlify-cms/draft

#10144 Création de 2022-05-31-bizdev.charge.e.de.deploiement.experimente.e dans Fiche de poste !
  content/_jobs/2022-05-31-bizdev.charge.e.de.deploiement.experimente.e.md
Labels: netlify-cms/pending_review

#10145 Création de 2022-05-31-developpeur.ou.developpeuse.python.django.experimente.e dans Fiche de poste !
  content/_jobs/2022-05-31-developpeur.ou.developpeuse.python.django.experimente.e.md
Labels: netlify-cms/draft

#10148 Mise à jour de 2022-05-31-developpeur.ou.developpeuse.python.django.experimente.e dans Fiche de poste
  content/_jobs/2022-05-31-developpeur.ou.developpeuse.python.django.experimente.e.md
Labels: netlify-cms/draft

#10149 Création de 2022-05-31-developpeur.ou.developpeuse.web.senior.e.-.4.jours.par.semaine dans Fiche de poste !
  content/_jobs/2022-05-31-developpeur.ou.developpeuse.web.senior.e.-.4.jours.par.semaine.md
Labels: netlify-cms/draft

#10150 Mise à jour de 2022-05-31-developpeur.ou.developpeuse.python.django.experimente.e dans Fiche de poste
  content/_jobs/2022-05-31-developpeur.ou.developpeuse.python.django.experimente.e.md
Labels: netlify-cms/draft

#10151 Mise à jour de 2022-05-31-developpeur.ou.developpeuse.web.senior.e.-.4.jours.par.semaine dans Fiche de poste
  content/_jobs/2022-05-31-developpeur.ou.developpeuse.web.senior.e.-.4.jours.par.semaine.md
Labels: netlify-cms/draft
