Repository betagouv/beta.gouv.fr, pull requests merged in 2022-10, with the labels that each got.

#11407 Mise à jour de octave.bory dans Membre
  content/_authors/octave.bory.md
Labels: netlify-cms/pending_review

#11419 Mise à jour de clemence.biffaud dans Membre
  content/_authors/clemence.biffaud.md
Labels: netlify-cms/pending_publish

#11420 Mise à jour de caroline.lawson dans Membre
  content/_authors/caroline.lawson.md
Labels: netlify-cms/draft

#11424 Mise à jour de marielaurence.leterme dans Membre
  content/_authors/marielaurence.leterme.md
Labels: netlify-cms/pending_review

#11425 Mise à jour de valerie.courcol dans Membre
  content/_authors/valerie.courcol.md
Labels: netlify-cms/pending_review

#11426 Mise à jour de laurie.premelcabic dans Membre
  content/_authors/laurie.premelcabic.md
Labels: netlify-cms/pending_review

#11430 Mise à jour de oilhi dans Produit
  content/_startups/oilhi.md
Labels: netlify-cms/pending_review

#11431 Mise à jour de marielaurence.leterme dans Membre
  content/_authors/marielaurence.leterme.md
Labels: netlify-cms/pending_review

#11432 Mise à jour de valerie.courcol dans Membre
  content/_authors/valerie.courcol.md
Labels: netlify-cms/pending_review

#11443 Mise à jour de camino dans Produit
  content/_startups/camino.md
Labels: netlify-cms/pending_review

#11475 Mise à jour de sophie.larroumet dans Membre
  content/_authors/sophie.larroumet.md
Labels: netlify-cms/draft

#11479 Mise à jour de acceslibre dans Produit
  content/_startups/acceslibre.md
Labels: netlify-cms/draft

#11355 Mise à jour de livio.lumbroso dans Membre
  content/_authors/livio.lumbroso.md
Labels: netlify-cms/pending_review

#11496 Mise à jour de simon.hamery dans Membre
  content/_authors/simon.hamery.md
Labels: netlify-cms/draft

#11503 Mise à jour de deveco dans Produit
  content/_startups/deveco.md
Labels: netlify-cms/pending_publish

#11467 Create Permis2visites.md
  content/_startups/Permis2visites.md
Labels: En attente review

#11508 Mise à jour de urbanvitaliz dans Produit
  content/_startups/urbanvitaliz.md
Labels: netlify-cms/pending_review

#11515 Création de rdv.mjd dans Produit !
  content/_startups/rdv.mjd.md
Labels: netlify-cms/pending_review

#11518 Création de frise.cpip dans Produit !
  content/_startups/frise.cpip.md
Labels: netlify-cms/pending_review

#11548 Mise à jour de 1000.jours dans Produit
  content/_startups/1000.jours.md
Labels: netlify-cms/draft

#11585 Mise à jour de maxine.sabater dans Membre
  content/_authors/maxine.sabater.md
Labels: netlify-cms/draft

#11602 Création de pcrs dans Produit !
  content/_startups/pcrs.md
Labels: netlify-cms/draft

#11610 Mise à jour de mehdi.hamamda dans Membre
  content/_authors/mehdi.hamamda.md
Labels: netlify-cms/draft

#11608 Mise à jour de philippe.zeinulabedin-rafi dans Membre
  content/_authors/philippe.zeinulabedin-rafi.md
Labels: netlify-cms/draft

#11607 Mise à jour de elodie.masse dans Membre
  content/_authors/elodie.masse.md
Labels: netlify-cms/draft

#11609 Mise à jour de claire.pacheco dans Membre
  content/_authors/claire.pacheco.md
Labels: netlify-cms/draft

#11606 Update alpha.md
  _pages/programme/formation/alpha.md
Labels: on_hold

#11701 Création de tarification.transports dans Produit !
  content/_startups/tarification.transports.md
Labels: netlify-cms/pending_review

#11514 Mise à jour de mes-aides dans Produit
  content/_startups/mes-aides.md
Labels: netlify-cms/draft
