Repository betagouv/beta.gouv.fr, pull requests merged in 2022-02, with the labels that each got.

#8754 Mise à jour de sgmas dans Incubateur
  content/_incubators/sgmas.md
Labels: netlify-cms/draft

#8549 Création de 2022-01-19-developpeuse.ou.developpeur.fullstack.a.dominante.django dans Fiche de poste !
  content/_jobs/2022-01-19-developpeuse.ou.developpeur.fullstack.a.dominante.django.md
Labels: netlify-cms/pending_review

#8827 Création de 2022-02-03-charge.e.de.deploiement dans Fiche de poste !
  content/_jobs/2022-02-03-charge.e.de.deploiement.md
Labels: netlify-cms/draft

#8830 Mise à jour de 2022-01-19-developpeuse.ou.developpeur.fullstack.a.dominante.django dans Fiche de poste
  content/_jobs/2022-01-19-developpeuse.ou.developpeur.fullstack.a.dominante.django.md
Labels: netlify-cms/draft

#8832 Mise à jour de 2022-01-10-developpeuse.-.developpeur.1 dans Fiche de poste
  content/_jobs/2022-01-10-developpeuse.-.developpeur.1.md
Labels: netlify-cms/draft

#8856 Mise à jour de jonathan.louis dans Membre
  content/_authors/jonathan.louis.md
Labels: netlify-cms/draft

#8883 Mise à jour de karine.delforge dans Membre
  content/_authors/karine.delforge.md
Labels: netlify-cms/pending_publish

#8885 Mise à jour de jeveuxaider dans Produit
  content/_startups/jeveuxaider.md
Labels: netlify-cms/pending_review

#8886 Mise à jour de api-engagement dans Produit
  content/_startups/api-engagement.md
Labels: netlify-cms/pending_review

#8887 Mise à jour de snu dans Produit
  content/_startups/snu.md
Labels: netlify-cms/pending_review

#8924 Mise à jour de 2022-01-19-developpeuse.ou.developpeur.fullstack.a.dominante.django dans Fiche de poste
  content/_jobs/2022-01-19-developpeuse.ou.developpeur.fullstack.a.dominante.django.md
Labels: netlify-cms/draft

#8925 Mise à jour de 2022-01-20-developpeuse.-.developpeur.fullstack.a.dominante.django dans Fiche de poste
  content/_jobs/2022-01-20-developpeuse.-.developpeur.fullstack.a.dominante.django.md
Labels: netlify-cms/pending_review

#8906 Création de 2022-02-09-charge.e.de.deploiement dans Fiche de poste !
  content/_jobs/2022-02-10-charge.e.de.deploiement-aides-jeunes.md
Labels: netlify-cms/pending_review

#8931 Mise à jour de mathieu.agopian dans Membre
  content/_authors/mathieu.agopian.md
Labels: netlify-cms/draft

#8937 Mise à jour de sofia.boulaarab dans Membre
  content/_authors/sofia.boulaarab.md
Labels: netlify-cms/pending_review

#8940 Mise à jour de 2022-02-03-charge.e.de.deploiement dans Fiche de poste
  content/_jobs/2022-02-03-charge.e.de.deploiement.md
Labels: netlify-cms/draft

#8951 Mise à jour de 2022-02-10-charge.e.de.deploiement-aides-jeunes dans Fiche de poste
  content/_jobs/2022-02-10-charge.e.de.deploiement-aides-jeunes.md
Labels: netlify-cms/pending_publish

#8957 Mise à jour de 2022-02-10-charge.e.de.deploiement-aides-jeunes dans Fiche de poste
  content/_jobs/2022-02-10-charge.e.de.deploiement-aides-jeunes.md
Labels: netlify-cms/pending_publish

#8960 Mise à jour de 2022-02-10-charge.e.de.deploiement-aides-jeunes dans Fiche de poste
  content/_jobs/2022-02-10-charge.e.de.deploiement-aides-jeunes.md
Labels: netlify-cms/draft

#8965 Mise à jour de 2022-02-10-charge.e.de.deploiement-aides-jeunes dans Fiche de poste
  content/_jobs/2022-02-10-charge.e.de.deploiement-aides-jeunes.md
Labels: netlify-cms/draft

#8967 Mise à jour de 2022-02-11-growth.hacker dans Fiche de poste
  content/_jobs/2022-02-11-growth.hacker.md
Labels: netlify-cms/pending_review

#8968 Mise à jour de 2022-02-11-growth.hacker dans Fiche de poste
  content/_jobs/2022-02-11-growth.hacker.md
Labels: netlify-cms/pending_review

#8988 Création de infrastructures.numeriques dans Produit !
  content/_startups/infrastructures.numeriques.md
Labels: netlify-cms/draft

#8991 Mise à jour de mediature dans Produit
  content/_startups/mediature.md
Labels: netlify-cms/pending_review

#8992 Mise à jour de mediature dans Produit
  content/_startups/mediature.md
Labels: netlify-cms/pending_review

#9034 Création de 2022-02-16-un.ou.une.ux.ui.designer dans Fiche de poste !
  content/_jobs/2022-02-16-un.ou.une.ux.ui.designer.md
Labels: netlify-cms/pending_review

#9037 Mise à jour de pass-emploi dans Produit
  content/_startups/pass-emploi.md
Labels: netlify-cms/pending_review

#8597 Mise à jour de 2022-01-10-developpeuse.-.developpeur dans Fiche de poste
  content/_jobs/2022-01-10-developpeuse.-.developpeur.md
Labels: netlify-cms/pending_publish

#8479 Création de devex dans Produit !
  content/_startups/devex.md
Labels: netlify-cms/pending_review

#8596 Mise à jour de 2022-01-10-designeuse.-.designer dans Fiche de poste
  content/_jobs/2022-01-10-designeuse.-.designer.md
Labels: netlify-cms/pending_publish

#9003 Mise à jour de vincent.agnano dans Membre
  content/_authors/vincent.agnano.md
Labels: netlify-cms/pending_review

#9127 Mise à jour de 2022-01-21-sppnaut-1ere-developpeuse.developpeur-fullstack dans Fiche de poste
  content/_jobs/2022-01-21-sppnaut-1ere-developpeuse.developpeur-fullstack.md
Labels: netlify-cms/draft

#9136 Mise à jour de 2022-01-18-product.designer.pour.le.service.national.universel dans Fiche de poste
  content/_jobs/2022-01-18-product.designer.pour.le.service.national.universel.md
Labels: netlify-cms/pending_review
