Repository betagouv/beta.gouv.fr, pull requests merged in 2022-06, with the labels that each got.

#10163 Mise à jour de archifiltre dans Produit
  content/_startups/archifiltre.md
Labels: netlify-cms/pending_publish

#10179 Mise à jour de 2022-04-27-une.developpeuse.ou.un.developpeur.full.stack.experimente.e dans Fiche de poste
  content/_jobs/2022-04-27-une.developpeuse.ou.un.developpeur.full.stack.experimente.e.md
Labels: netlify-cms/pending_review

#10197 Mise à jour de 2022-05-31-developpeur.ou.developpeuse.web.senior.e.-.4.jours.par.semaine dans Fiche de poste
  content/_jobs/2022-05-31-developpeur.ou.developpeuse.web.senior.e.-.4.jours.par.semaine.md
Labels: netlify-cms/pending_review

#10201 Mise à jour de 2022-05-11-designeuse.ou.designeur.ui dans Fiche de poste
  content/_jobs/2022-05-11-designeuse.ou.designeur.ui.md
Labels: netlify-cms/draft

#10064 Ay11 understandable without css homepage
  assets/home/coach.svg
  assets/home/coach_back.svg
  assets/home/deploiement.svg
  assets/home/deploiement_back.svg
  assets/home/design.svg
  assets/home/design_back.svg
  assets/home/dev.svg
  assets/home/dev_back.svg
  assets/home/intra.svg
  assets/home/intra_back.svg
  assets/home/produit.svg
  assets/home/produit_back.svg
  img/startups/mon-entreprise.png
  img/startups/pix.png
  img/startups/transport.png
Labels: a11y

#10231 Test Fiche Post Lucas
  content/_jobs/2022-03-01-tchap-devops.md
Labels: netlify-cms/draft

#10235 Mise à jour de 2022-05-31-developpeur-se.full.stack.4.jours.par.semaine dans Fiche de poste
  content/_jobs/2022-05-31-developpeur-se.full.stack.4.jours.par.semaine.md
Labels: netlify-cms/pending_review

#10242 Mise à jour de 2022-01-10-itou-data-analyst dans Fiche de poste
  content/_jobs/2022-01-10-itou-data-analyst.md
Labels: netlify-cms/draft

#10258 Mise à jour de 2022-04-26-bizdev-collectif-objets dans Fiche de poste
  content/_jobs/2022-04-26-bizdev-collectif-objets.md
Labels: netlify-cms/pending_review

#10164 Création de 2022-06-01-developpeuse.principale.-.developpeur.principal dans Fiche de poste !
  content/_jobs/2022-06-01-developpeuse.principale.-.developpeur.principal.md
Labels: netlify-cms/pending_publish

#10268 Mise à jour de 2021-11-22-charge-e.du.customer.success dans Fiche de poste
  content/_jobs/2021-11-22-charge-e.du.customer.success.md
Labels: netlify-cms/pending_review

#10363 Mise à jour de 2022-04-15-charge.e.de.deploiement.aupres.des.associations.pour.jeveuxaider-gouv-fr dans Fiche de poste
  content/_jobs/2022-04-15-charge.e.de.deploiement.aupres.des.associations.pour.jeveuxaider-gouv-fr.md
Labels: netlify-cms/draft

#10395 Création de 2022-06-16-chargee.ou.charge.de.deploiement.stage dans Fiche de poste !
  content/_jobs/2022-06-16-chargee.ou.charge.de.deploiement.stage.md
Labels: netlify-cms/pending_review

#10396 Mise à jour de 2022-06-16-chargee.ou.charge.de.deploiement.stage dans Fiche de poste
  content/_jobs/2022-06-16-chargee.ou.charge.de.deploiement.stage.md
Labels: netlify-cms/pending_review

#10403 Mise à jour de 2022-04-28-chef.fe.de.produit.pour.le.pilotage.de.linclusion dans Fiche de poste
  content/_jobs/2022-04-28-chef.fe.de.produit.pour.le.pilotage.de.linclusion.md
Labels: netlify-cms/draft

#10416 Mise à jour de 2021-07-05-camino-beta-gouv-fr.recrute.un.developpeur.se.full.stack dans Fiche de poste
  content/_jobs/2021-07-05-camino-beta-gouv-fr.recrute.un.developpeur.se.full.stack.md
Labels: netlify-cms/pending_publish

#10399 Création de 2022-06-17-developpeur.se.backend.web.-.python.fastapi dans Fiche de poste !
  content/_jobs/2022-06-17-developpeur.se.backend.web.-.python.fastapi.md
Labels: netlify-cms/draft

#10402 Création de 2022-06-17-charge.ou.chargee.de.deploiement.pour.les.assistants.et.simulateurs.de.mon-entreprise-urssaf-fr dans Fiche de poste !
  content/_jobs/2022-06-17-charge.ou.chargee.de.deploiement.pour.les.assistants.et.simulateurs.de.mon-entreprise-urssaf-fr.md
Labels: netlify-cms/pending_publish

#10450 add title for target blank link in footer
  _includes/footer.html
Labels: a11y

#10451 remove irrelevant link a11y
  _pages/approche.md
Labels: a11y

#10468 fix alternative image for accessibility
  _pages/approche.md
Labels: a11y

#10172 Mise à jour de 2022-03-11-developpeur.ou.une.developpeuse.front dans Fiche de poste
  content/_jobs/2022-03-11-developpeur.ou.une.developpeuse.front.md
Labels: netlify-cms/pending_review

#10051 Mise à jour de 2022-05-12-charge-e.de.portefeuille.data.a.lincubateur.des.territoires dans Fiche de poste
  content/_jobs/2022-05-12-charge-e.de.portefeuille.data.a.lincubateur.des.territoires.md
Labels: netlify-cms/pending_review

#10461 fix title order and remove not DSFR class for styling title
  _pages/approche.md
  assets/main.css
Labels: a11y

#10367 Mise à jour de leximpact dans Produit
  content/_startups/leximpact.md
  img/startups/leximpact.png
Labels: netlify-cms/pending_review

#10577 add size in svg logo file and remove inline style for header and footer
  _includes/footer.html
  _includes/header.html
  assets/additional/images/logo-betagouvfr.svg
  assets/main.css
Labels: a11y
