Repository betagouv/beta.gouv.fr, pull requests merged in 2023-05, with the labels that each got.

#14071 Mise à jour de jonathan.bourguignon dans Membre
  content/_authors/jonathan.bourguignon.md
Labels: netlify-cms/pending_review

#14072 Mise à jour de thibaut.faucon dans Membre
  content/_authors/thibaut.faucon.md
Labels: netlify-cms/pending_review

#14010 Création de bases.adresses.locales dans Produit !
  content/_startups/bases.adresses.locales.md
  img/netlifycms/mesadresses.png
Labels: netlify-cms/pending_review

#14149 Mise à jour de stephane.legouffe dans Membre
  content/_authors/stephane.legouffe.md
Labels: netlify-cms/pending_publish

#14170 Mise à jour de rafraichir.les.villes dans Produit
  content/_startups/rafraichir.les.villes.md
Labels: netlify-cms/pending_review

#14233 Mise à jour de tan.letellier dans Membre
  content/_authors/tan.letellier.md
Labels: netlify-cms/pending_publish

#14235 Mise à jour de a-just dans Produit
  content/_startups/a-just.md
Labels: netlify-cms/pending_publish

#14236 Mise à jour de fanny.blanc dans Membre
  content/_authors/fanny.blanc.md
Labels: netlify-cms/pending_publish

#14248 Mise à jour de tan.letellier dans Membre
  content/_authors/tan.letellier.md
Labels: netlify-cms/pending_review

#14267 Création de que.faire.de.mes.objets dans Produit !
  content/_startups/que.faire.de.mes.objets.md
Labels: netlify-cms/draft

#14270 Mise à jour de mobicouts dans Produit
  content/_startups/mobicouts.md
Labels: netlify-cms/draft

#14286 Mise à jour de arnaud.benede dans Membre
  content/_authors/arnaud.benede.md
Labels: netlify-cms/draft

#14310 Mise à jour de sparte dans Produit
  content/_startups/sparte.md
Labels: netlify-cms/pending_review

#14311 Mise à jour de louis.laroche dans Membre
  content/_authors/louis.laroche.md
Labels: netlify-cms/pending_review

#14312 Mise à jour de aquaculteurs.marins dans Produit
  content/_startups/aquaculteurs.marins.md
Labels: netlify-cms/pending_review

#14313 Mise à jour de julie.benzoni dans Membre
  content/_authors/julie.benzoni.md
Labels: netlify-cms/pending_review

#14318 Création de mediation.logement dans Produit !
  content/_startups/mediation.logement.md
Labels: netlify-cms/pending_review

#14314 Mise à jour de amandine.collard dans Membre
  content/_authors/amandine.collard.md
Labels: netlify-cms/pending_review

#14289 Mise à jour de noemie.desard dans Membre
  content/_authors/noemie.desard.md
Labels: netlify-cms/draft

#14287 Mise à jour de thomas.blazy dans Membre
  content/_authors/thomas.blazy.md
Labels: netlify-cms/draft

#14321 Mise à jour de louis.laroche dans Membre
  content/_authors/louis.laroche.md
Labels: netlify-cms/pending_review

#14319 Mise à jour de remy.roche dans Membre
  content/_authors/remy.roche.md
Labels: netlify-cms/pending_review

#14292 Création de impact.co2 dans Produit !
  content/_startups/impact.co2.md
Labels: netlify-cms/pending_review

#14345 Mise à jour de impact.co2 dans Produit
  content/_startups/impact.co2.md
Labels: netlify-cms/pending_review

#14350 Mise à jour de maxine.sabater dans Membre
  content/_authors/maxine.sabater.md
Labels: netlify-cms/pending_review

#14366 Mise à jour de maxine.sabater dans Membre
  content/_authors/maxine.sabater.md
Labels: netlify-cms/pending_review

#14364 Mise à jour de david.boureau dans Membre
  content/_authors/david.boureau.md
Labels: netlify-cms/pending_review

#14365 Mise à jour de laura.dussier dans Membre
  content/_authors/laura.dussier.md
Labels: netlify-cms/pending_review

#14363 Mise à jour de clemence.martin dans Membre
  content/_authors/clemence.martin.md
Labels: netlify-cms/pending_review

#14411 Mise à jour de laurie.premelcabic dans Membre
  content/_authors/laurie.premelcabic.md
Labels: netlify-cms/pending_review

#14454 Mise à jour de nathalie.reyre dans Membre
  content/_authors/nathalie.reyre.md
Labels: netlify-cms/pending_review

#14467 Mise à jour de penelope.liot dans Membre
  content/_authors/penelope.liot.md
Labels: netlify-cms/draft
