Repository betagouv/beta.gouv.fr, pull requests merged in 2023-07, with the labels that each got.

#14839 Création de basegun dans Produit !
  content/_startups/basegun.md
Labels: netlify-cms/pending_review

#14850 Mise à jour de lab-mi dans Incubateur
  content/_incubators/lab-mi.md
Labels: netlify-cms/pending_review

#14762 Mise à jour de dedale dans Produit
  content/_startups/dedale.md
Labels: netlify-cms/pending_review

#14946 Création de apma.-.kbks.-.kf dans Produit !
  content/_startups/apma.-.kbks.-.kf.md
Labels: netlify-cms/pending_review

#14961 Mise à jour de apma.-.kbks.-.kf dans Produit
  content/_startups/apma.-.kbks.-.kf.md
Labels: netlify-cms/draft

#14980 Mise à jour de joel.figueres dans Membre
  content/_authors/joel.figueres.md
Labels: netlify-cms/pending_review

#14981 Mise à jour de emmanuel.bellity dans Membre
  content/_authors/emmanuel.bellity.md
Labels: netlify-cms/pending_review

#14982 Mise à jour de evalpro dans Produit
  content/_startups/evalpro.md
Labels: netlify-cms/draft

#14983 Mise à jour de emmanuel.bellity dans Membre
  content/_authors/emmanuel.bellity.md
Labels: netlify-cms/draft

#14984 Mise à jour de joel.figueres dans Membre
  content/_authors/joel.figueres.md
Labels: netlify-cms/draft

#14986 Mise à jour de evalpro dans Produit
  content/_startups/evalpro.md
Labels: netlify-cms/pending_review

#15012 Mise à jour de arnaud.jacob dans Membre
  content/_authors/arnaud.jacob.md
Labels: netlify-cms/pending_publish

#15030 Création de astree dans Produit !
  content/_startups/astree.md
Labels: netlify-cms/pending_review

#14249 Mise à jour de mobiville dans Produit
  content/_startups/mobiville.md
Labels: netlify-cms/pending_publish

#14252 Mise à jour de pole-emploi dans Incubateur
  content/_incubators/pole-emploi.md
Labels: netlify-cms/pending_review

#14326 Création de prelevements.deau dans Produit !
  content/_startups/prelevements.deau.md
Labels: netlify-cms/pending_publish

#15104 Création de boite.aux.lettres dans Produit !
  content/_startups/boite.aux.lettres.md
Labels: netlify-cms/pending_review

#15106 Mise à jour de anne-camille.monet dans Membre
  content/_authors/anne-camille.monet.md
Labels: netlify-cms/pending_review

#15107 Mise à jour de livia.ribeiro dans Membre
  content/_authors/livia.ribeiro.md
Labels: netlify-cms/draft

#15112 Mise à jour de boite.aux.lettres dans Produit
  content/_startups/boite.aux.lettres.md
Labels: netlify-cms/pending_review

#15113 Mise à jour de antoine.bigard dans Membre
  content/_authors/antoine.bigard.md
Labels: netlify-cms/pending_review

#15114 Mise à jour de moroine.bentefrit dans Membre
  content/_authors/moroine.bentefrit.md
Labels: netlify-cms/pending_review
