Repository betagouv/beta.gouv.fr, pull requests merged in 2023-01, with the labels that each got.

#12646 Mise à jour de vikie.ache dans Membre
  content/_authors/vikie.ache.md
Labels: netlify-cms/draft

#12724 Mise à jour de uvf-numerique dans Produit
  content/_startups/uvf-numerique.md
Labels: netlify-cms/pending_review

#12740 Mise à jour de potentiel dans Produit
  content/_startups/potentiel.md
Labels: netlify-cms/pending_review

#12783 Mise à jour de julie.benzoni dans Membre
  content/_authors/julie.benzoni.md
Labels: netlify-cms/pending_review

#12784 Mise à jour de pierre-antoine.duchateau dans Membre
  content/_authors/pierre-antoine.duchateau.md
Labels: netlify-cms/pending_review

#12785 Mise à jour de delphine.raymond dans Membre
  content/_authors/delphine.raymond.md
Labels: netlify-cms/pending_review

#12786 Mise à jour de florian.de-la-comble dans Membre
  content/_authors/florian.de-la-comble.md
Labels: netlify-cms/pending_review

#12787 Mise à jour de philippe.jary dans Membre
  content/_authors/philippe.jary.md
Labels: netlify-cms/pending_review

#12803 Mise à jour de laurie.premelcabic dans Membre
  content/_authors/laurie.premelcabic.md
Labels: netlify-cms/pending_review

#12772 Mise à jour de romin dans Produit
  content/_startups/romin.md
Labels: netlify-cms/draft

#12310 Mise à jour de la date de fin de mission pour cyrille.corbin.md
  content/_authors/cyrille.corbin.md
Labels: En discussion

#12845 Mise à jour de chloe.moser dans Membre
  content/_authors/chloe.moser.md
Labels: netlify-cms/pending_publish

#12846 Mise à jour de mehdi.louraoui dans Membre
  content/_authors/mehdi.louraoui.md
Labels: netlify-cms/pending_publish

#12939 Création de dea dans Organisation !
  content/_organisations/dea.md
Labels: netlify-cms/draft

#13000 Mise à jour de karine.delforge dans Membre
  content/_authors/karine.delforge.md
Labels: netlify-cms/pending_publish

#13007 Mise à jour de dora dans Produit
  content/_startups/dora.md
Labels: netlify-cms/draft

#13008 Mise à jour de dora dans Produit
  content/_startups/dora.md
Labels: netlify-cms/draft
