Repository betagouv/beta.gouv.fr, pull requests merged in 2023-06, with the labels that each got.

#14573 Mise à jour de clemence.martin dans Membre
  content/_authors/clemence.martin.md
Labels: netlify-cms/draft

#14618 Mise à jour de amandine.collard dans Membre
  content/_authors/amandine.collard.md
Labels: netlify-cms/pending_review

#14635 Mise à jour de impact.co2 dans Produit
  content/_startups/impact.co2.md
  img/netlifycms/capture.d.e.cran.2023-06-09.a.22.14.06.png
Labels: netlify-cms/pending_review

#14636 Mise à jour de impact.co2 dans Produit
  content/_startups/impact.co2.md
  img/netlifycms/capture.d.e.cran.2023-06-09.a.23.07.15.png
Labels: netlify-cms/pending_review

#14633 Création de pacoupa dans Produit !
  content/_startups/pacoupa.md
Labels: netlify-cms/draft

#14661 Mise à jour de pacoupa dans Produit
  content/_startups/pacoupa.md
Labels: netlify-cms/pending_publish

#14778 Création de signalementenvironnement dans Produit !
  content/_startups/signalementenvironnement.md
Labels: netlify-cms/pending_review

#14786 Mise à jour de signalementenvironnement dans Produit
  content/_startups/signalementenvironnement.md
Labels: netlify-cms/pending_review

#14840 Mise à jour de anael.delorme dans Membre
  content/_authors/anael.delorme.md
Labels: netlify-cms/pending_review

#14389 Mise à jour de romin dans Produit
  content/_startups/romin.md
Labels: netlify-cms/pending_review

#14900 Création de suite.collaborative dans Produit !
  content/_startups/suite.collaborative.md
Labels: netlify-cms/pending_review
