Repository betagouv/beta.gouv.fr, pull requests merged in 2023-09, with the labels that each got.

#15416 Mise à jour de aurelie.manginot dans Membre
  content/_authors/aurelie.manginot.md
Labels: netlify-cms/pending_publish

#15492 Création de vie.chere dans Produit !
  content/_startups/vie.chere.md
Labels: netlify-cms/draft

#15523 Mise à jour de pierre.rousseau dans Membre
  content/_authors/pierre.rousseau.md
Labels: netlify-cms/pending_review

#15522 Mise à jour de jafer dans Produit
  content/_startups/jafer.md
Labels: netlify-cms/pending_review

#15541 Mise à jour de anael.delorme dans Membre
  content/_authors/anael.delorme.md
Labels: netlify-cms/pending_review

#15558 Création de parasport dans Produit !
  content/_startups/parasport.md
  schema/startups.yml
Labels: netlify-cms/pending_review

#15597 Mise à jour de anael.delorme dans Membre
  content/_authors/anael.delorme.md
Labels: netlify-cms/pending_review

#15641 Mise à jour de amale.habibi dans Membre
  content/_authors/amale.habibi.md
Labels: netlify-cms/draft

#15680 Mise à jour de ecobalyse dans Produit
  content/_startups/ecobalyse.md
Labels: netlify-cms/draft

#14169 Création de agora.1 dans Produit !
  content/_startups/agora.md
Labels: netlify-cms/pending_review

#15706 Mise à jour de ban dans Produit
  content/_startups/ban.md
Labels: netlify-cms/draft

#15716 Mise à jour de bases.adresses.locales dans Produit
  content/_startups/bases.adresses.locales.md
Labels: netlify-cms/draft
