Repository betagouv/beta.gouv.fr, pull requests merged in 2024-01, with the labels that each got.

#17598 Ajout du site EIG au schéma pluriannuel
  _pages/accessibilite/schema-pluriannuel.md
Labels: 🔥 FEATURE

#17610 Update alexis.boudard.md
  content/_authors/alexis.boudard.md
Labels: En attente review

#17447 Optimisation taille d'image Scalingo
  .slugignore
Labels: ⚙️ OPS

#16244 Optimisation configuration Nginx
  servers.conf.erb
Labels: ⚙️ OPS

#17719 Update nadege.vaugrenard.md
  content/_authors/nadege.vaugrenard.md
Labels: En attente review

#17759 Update magalie.dartus.md
  content/_authors/magalie.dartus.md
Labels: En attente review

#17665 feat: add national_impact filter on page "realisations"
  _includes/startups-filters.html
  _layouts/realisations.html
  _layouts/startups.html
  _plugins/incubators.rb
  _plugins/national_impact.rb
  assets/additional/js/search-startup.js
Labels: 🔥 FEATURE

#17578 feat: ajoute la page eig
  _data/menu.yml
  _layouts/eig.html
  _pages/eig.md
  assets/images/eig-home.svg
  package-lock.json
  package.json
Labels: 🔥 FEATURE

#17805 Mise à jour de yoan.pintas dans Membre
  content/_authors/yoan.pintas.md
Labels: netlify-cms/pending_review

#15398 feat(api): add sponsors and organisations, add authors details
  api/v2.6/authors.json
  api/v2.6/incubators.json
  api/v2.6/jobs.json
  api/v2.6/organisations.json
  api/v2.6/sponsors.json
  api/v2.6/startups.csv
  api/v2.6/startups.json
  api/v2.6/startups_details.json
Labels: 🔥 FEATURE

#17908 Mise à jour de mon-suivi-justice dans Produit
  content/_startups/mon-suivi-justice.md
Labels: netlify-cms/draft

#17913 Mise à jour de mon-suivi-justice dans Produit
  content/_startups/mon-suivi-justice.md
Labels: netlify-cms/draft

#17931 Mise à jour de mon-suivi-justice dans Produit
  content/_startups/mon-suivi-justice.md
Labels: netlify-cms/draft
