Repository betagouv/beta.gouv.fr, pull requests merged in 2024-05, with the labels that each got.

#19527 Update raphael.mucha.md
  content/_authors/raphael.mucha.md
Labels: En attente review

#19582 Mise à jour de place-des-entreprises dans Produit
  content/_startups/place-des-entreprises.md
Labels: netlify-cms/pending_review

#19575 Mise à jour de lannuaire.des.collectivites dans Produit
  content/_startups/lannuaire.des.collectivites.md
Labels: netlify-cms/draft

#19778 Mise à jour de aplus dans Produit
  content/_startups/aplus.md
Labels: netlify-cms/draft

#19813 Mise à jour de rdv-service-public dans Produit
  content/_startups/rdv-service-public.md
Labels: netlify-cms/draft
